// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/blogger.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 视频博主维度数据 DTO
// 视频博主维度数据 DTO
type BloggerDTO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 博主ID
	BloggerId int64 `protobuf:"varint,1,opt,name=blogger_id,json=bloggerId,proto3" json:"blogger_id,omitempty"`
	// 创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 昵称
	BloggerUid string `protobuf:"bytes,4,opt,name=blogger_uid,json=bloggerUid,proto3" json:"blogger_uid,omitempty"`
	// 头像URL
	BloggerName string `protobuf:"bytes,5,opt,name=blogger_name,json=bloggerName,proto3" json:"blogger_name,omitempty"`
	// 头像URL
	BloggerAvatar string `protobuf:"bytes,6,opt,name=blogger_avatar,json=bloggerAvatar,proto3" json:"blogger_avatar,omitempty"`
	// 粉丝数量
	BloggerFansNum int64 `protobuf:"varint,7,opt,name=blogger_fans_num,json=bloggerFansNum,proto3" json:"blogger_fans_num,omitempty"`
	// 标签
	BloggerTag    string `protobuf:"bytes,8,opt,name=blogger_tag,json=bloggerTag,proto3" json:"blogger_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloggerDTO) Reset() {
	*x = BloggerDTO{}
	mi := &file_v1_blogger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloggerDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloggerDTO) ProtoMessage() {}

func (x *BloggerDTO) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blogger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloggerDTO.ProtoReflect.Descriptor instead.
func (*BloggerDTO) Descriptor() ([]byte, []int) {
	return file_v1_blogger_proto_rawDescGZIP(), []int{0}
}

func (x *BloggerDTO) GetBloggerId() int64 {
	if x != nil {
		return x.BloggerId
	}
	return 0
}

func (x *BloggerDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BloggerDTO) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BloggerDTO) GetBloggerUid() string {
	if x != nil {
		return x.BloggerUid
	}
	return ""
}

func (x *BloggerDTO) GetBloggerName() string {
	if x != nil {
		return x.BloggerName
	}
	return ""
}

func (x *BloggerDTO) GetBloggerAvatar() string {
	if x != nil {
		return x.BloggerAvatar
	}
	return ""
}

func (x *BloggerDTO) GetBloggerFansNum() int64 {
	if x != nil {
		return x.BloggerFansNum
	}
	return 0
}

func (x *BloggerDTO) GetBloggerTag() string {
	if x != nil {
		return x.BloggerTag
	}
	return ""
}

// 分页查询视频博主请求
type ListBloggersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页参数
	Page *PageRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// 模糊查询关键字 (将作用于 blogger_name 字段)
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// 排序字段 (例如: "blogger_fans_num", "updated_at")
	SortBy string `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// 排序方向 (ASC / DESC)
	SortOrder     SortOrder `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBloggersRequest) Reset() {
	*x = ListBloggersRequest{}
	mi := &file_v1_blogger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBloggersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBloggersRequest) ProtoMessage() {}

func (x *ListBloggersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blogger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBloggersRequest.ProtoReflect.Descriptor instead.
func (*ListBloggersRequest) Descriptor() ([]byte, []int) {
	return file_v1_blogger_proto_rawDescGZIP(), []int{1}
}

func (x *ListBloggersRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListBloggersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListBloggersRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListBloggersRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_UNSORTED
}

// 分页查询视频博主响应
type ListBloggersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResponse          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Bloggers      []*BloggerDTO          `protobuf:"bytes,2,rep,name=bloggers,proto3" json:"bloggers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBloggersResponse) Reset() {
	*x = ListBloggersResponse{}
	mi := &file_v1_blogger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBloggersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBloggersResponse) ProtoMessage() {}

func (x *ListBloggersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blogger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBloggersResponse.ProtoReflect.Descriptor instead.
func (*ListBloggersResponse) Descriptor() ([]byte, []int) {
	return file_v1_blogger_proto_rawDescGZIP(), []int{2}
}

func (x *ListBloggersResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListBloggersResponse) GetBloggers() []*BloggerDTO {
	if x != nil {
		return x.Bloggers
	}
	return nil
}

type BloggerQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 博主ID
	BloggerId     int64 `protobuf:"varint,1,opt,name=blogger_id,json=bloggerId,proto3" json:"blogger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloggerQueryRequest) Reset() {
	*x = BloggerQueryRequest{}
	mi := &file_v1_blogger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloggerQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloggerQueryRequest) ProtoMessage() {}

func (x *BloggerQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blogger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloggerQueryRequest.ProtoReflect.Descriptor instead.
func (*BloggerQueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_blogger_proto_rawDescGZIP(), []int{3}
}

func (x *BloggerQueryRequest) GetBloggerId() int64 {
	if x != nil {
		return x.BloggerId
	}
	return 0
}

type BloggerQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogger       *BloggerDTO            `protobuf:"bytes,1,opt,name=blogger,proto3" json:"blogger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloggerQueryResponse) Reset() {
	*x = BloggerQueryResponse{}
	mi := &file_v1_blogger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloggerQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloggerQueryResponse) ProtoMessage() {}

func (x *BloggerQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blogger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloggerQueryResponse.ProtoReflect.Descriptor instead.
func (*BloggerQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_blogger_proto_rawDescGZIP(), []int{4}
}

func (x *BloggerQueryResponse) GetBlogger() *BloggerDTO {
	if x != nil {
		return x.Blogger
	}
	return nil
}

var File_v1_blogger_proto protoreflect.FileDescriptor

const file_v1_blogger_proto_rawDesc = "" +
	"\n" +
	"\x10v1/blogger.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rv1/page.proto\"\xd7\x02\n" +
	"\n" +
	"BloggerDTO\x12\x1d\n" +
	"\n" +
	"blogger_id\x18\x01 \x01(\x03R\tbloggerId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vblogger_uid\x18\x04 \x01(\tR\n" +
	"bloggerUid\x12!\n" +
	"\fblogger_name\x18\x05 \x01(\tR\vbloggerName\x12%\n" +
	"\x0eblogger_avatar\x18\x06 \x01(\tR\rbloggerAvatar\x12(\n" +
	"\x10blogger_fans_num\x18\a \x01(\x03R\x0ebloggerFansNum\x12\x1f\n" +
	"\vblogger_tag\x18\b \x01(\tR\n" +
	"bloggerTag\"\x91\x01\n" +
	"\x13ListBloggersRequest\x12 \n" +
	"\x04page\x18\x01 \x01(\v2\f.PageRequestR\x04page\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12)\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\n" +
	".SortOrderR\tsortOrder\"b\n" +
	"\x14ListBloggersResponse\x12!\n" +
	"\x04page\x18\x01 \x01(\v2\r.PageResponseR\x04page\x12'\n" +
	"\bbloggers\x18\x02 \x03(\v2\v.BloggerDTOR\bbloggers\"4\n" +
	"\x13BloggerQueryRequest\x12\x1d\n" +
	"\n" +
	"blogger_id\x18\x01 \x01(\x03R\tbloggerId\"=\n" +
	"\x14BloggerQueryResponse\x12%\n" +
	"\ablogger\x18\x01 \x01(\v2\v.BloggerDTOR\ablogger2\xc6\x01\n" +
	"\x0eBloggerService\x12Y\n" +
	"\n" +
	"GetBlogger\x12\x14.BloggerQueryRequest\x1a\x15.BloggerQueryResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/bloggers/detail\x12Y\n" +
	"\fListBloggers\x12\x14.ListBloggersRequest\x1a\x15.ListBloggersResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/bloggers/listB\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_blogger_proto_rawDescOnce sync.Once
	file_v1_blogger_proto_rawDescData []byte
)

func file_v1_blogger_proto_rawDescGZIP() []byte {
	file_v1_blogger_proto_rawDescOnce.Do(func() {
		file_v1_blogger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_blogger_proto_rawDesc), len(file_v1_blogger_proto_rawDesc)))
	})
	return file_v1_blogger_proto_rawDescData
}

var file_v1_blogger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_blogger_proto_goTypes = []any{
	(*BloggerDTO)(nil),            // 0: BloggerDTO
	(*ListBloggersRequest)(nil),   // 1: ListBloggersRequest
	(*ListBloggersResponse)(nil),  // 2: ListBloggersResponse
	(*BloggerQueryRequest)(nil),   // 3: BloggerQueryRequest
	(*BloggerQueryResponse)(nil),  // 4: BloggerQueryResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*PageRequest)(nil),           // 6: PageRequest
	(SortOrder)(0),                // 7: SortOrder
	(*PageResponse)(nil),          // 8: PageResponse
}
var file_v1_blogger_proto_depIdxs = []int32{
	5, // 0: BloggerDTO.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: BloggerDTO.updated_at:type_name -> google.protobuf.Timestamp
	6, // 2: ListBloggersRequest.page:type_name -> PageRequest
	7, // 3: ListBloggersRequest.sort_order:type_name -> SortOrder
	8, // 4: ListBloggersResponse.page:type_name -> PageResponse
	0, // 5: ListBloggersResponse.bloggers:type_name -> BloggerDTO
	0, // 6: BloggerQueryResponse.blogger:type_name -> BloggerDTO
	3, // 7: BloggerService.GetBlogger:input_type -> BloggerQueryRequest
	1, // 8: BloggerService.ListBloggers:input_type -> ListBloggersRequest
	4, // 9: BloggerService.GetBlogger:output_type -> BloggerQueryResponse
	2, // 10: BloggerService.ListBloggers:output_type -> ListBloggersResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_v1_blogger_proto_init() }
func file_v1_blogger_proto_init() {
	if File_v1_blogger_proto != nil {
		return
	}
	file_v1_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_blogger_proto_rawDesc), len(file_v1_blogger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_blogger_proto_goTypes,
		DependencyIndexes: file_v1_blogger_proto_depIdxs,
		MessageInfos:      file_v1_blogger_proto_msgTypes,
	}.Build()
	File_v1_blogger_proto = out.File
	file_v1_blogger_proto_goTypes = nil
	file_v1_blogger_proto_depIdxs = nil
}
