// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/fetcher.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hello 方法的请求
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_v1_fetcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_fetcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_v1_fetcher_proto_rawDescGZIP(), []int{0}
}

// Hello 方法的响应
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_v1_fetcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_fetcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_v1_fetcher_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_fetcher_proto protoreflect.FileDescriptor

const file_v1_fetcher_proto_rawDesc = "" +
	"\n" +
	"\x10v1/fetcher.proto\x1a\x1cgoogle/api/annotations.proto\"\x0e\n" +
	"\fHelloRequest\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2A\n" +
	"\aFetcher\x126\n" +
	"\x05Hello\x12\r.HelloRequest\x1a\v.HelloReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/helloB\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_fetcher_proto_rawDescOnce sync.Once
	file_v1_fetcher_proto_rawDescData []byte
)

func file_v1_fetcher_proto_rawDescGZIP() []byte {
	file_v1_fetcher_proto_rawDescOnce.Do(func() {
		file_v1_fetcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_fetcher_proto_rawDesc), len(file_v1_fetcher_proto_rawDesc)))
	})
	return file_v1_fetcher_proto_rawDescData
}

var file_v1_fetcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_fetcher_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: HelloRequest
	(*HelloReply)(nil),   // 1: HelloReply
}
var file_v1_fetcher_proto_depIdxs = []int32{
	0, // 0: Fetcher.Hello:input_type -> HelloRequest
	1, // 1: Fetcher.Hello:output_type -> HelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_fetcher_proto_init() }
func file_v1_fetcher_proto_init() {
	if File_v1_fetcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_fetcher_proto_rawDesc), len(file_v1_fetcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_fetcher_proto_goTypes,
		DependencyIndexes: file_v1_fetcher_proto_depIdxs,
		MessageInfos:      file_v1_fetcher_proto_msgTypes,
	}.Build()
	File_v1_fetcher_proto = out.File
	file_v1_fetcher_proto_goTypes = nil
	file_v1_fetcher_proto_depIdxs = nil
}
