// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/product.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品维度数据 DTO
type ProductDTO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品 ID
	GoodsId string `protobuf:"bytes,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt string `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 商品标题
	GoodsTitle string `protobuf:"bytes,4,opt,name=goods_title,json=goodsTitle,proto3" json:"goods_title,omitempty"`
	// 商品封面 URL
	GoodsCoverUrl string `protobuf:"bytes,5,opt,name=goods_cover_url,json=goodsCoverUrl,proto3" json:"goods_cover_url,omitempty"`
	// 商品价格范围
	GoodsPriceRange string `protobuf:"bytes,6,opt,name=goods_price_range,json=goodsPriceRange,proto3" json:"goods_price_range,omitempty"`
	// 商品价格
	GoodsPrice float64 `protobuf:"fixed64,7,opt,name=goods_price,json=goodsPrice,proto3" json:"goods_price,omitempty"`
	// 成本占比
	CosRatio string `protobuf:"bytes,8,opt,name=cos_ratio,json=cosRatio,proto3" json:"cos_ratio,omitempty"`
	// 佣金价格
	CommissionPrice string `protobuf:"bytes,9,opt,name=commission_price,json=commissionPrice,proto3" json:"commission_price,omitempty"`
	// 店铺名称
	ShopName string `protobuf:"bytes,10,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	// 品牌名称
	BrandName string `protobuf:"bytes,11,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	// 商品类目名称
	CategoryNames string `protobuf:"bytes,12,opt,name=category_names,json=categoryNames,proto3" json:"category_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDTO) Reset() {
	*x = ProductDTO{}
	mi := &file_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDTO) ProtoMessage() {}

func (x *ProductDTO) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDTO.ProtoReflect.Descriptor instead.
func (*ProductDTO) Descriptor() ([]byte, []int) {
	return file_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductDTO) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *ProductDTO) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductDTO) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ProductDTO) GetGoodsTitle() string {
	if x != nil {
		return x.GoodsTitle
	}
	return ""
}

func (x *ProductDTO) GetGoodsCoverUrl() string {
	if x != nil {
		return x.GoodsCoverUrl
	}
	return ""
}

func (x *ProductDTO) GetGoodsPriceRange() string {
	if x != nil {
		return x.GoodsPriceRange
	}
	return ""
}

func (x *ProductDTO) GetGoodsPrice() float64 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *ProductDTO) GetCosRatio() string {
	if x != nil {
		return x.CosRatio
	}
	return ""
}

func (x *ProductDTO) GetCommissionPrice() string {
	if x != nil {
		return x.CommissionPrice
	}
	return ""
}

func (x *ProductDTO) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ProductDTO) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *ProductDTO) GetCategoryNames() string {
	if x != nil {
		return x.CategoryNames
	}
	return ""
}

// 分页查询商品请求
type ListProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页参数
	Page *PageRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// 模糊查询关键字 (将作用于 goods_title 字段)
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// 排序字段 (例如: "created_at", "goods_price")
	SortBy string `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// 排序方向（1: ASC, 2: DESC）
	SortOrder     SortOrder `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListProductsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListProductsRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_UNSORTED
}

// 分页查询商品响应
type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResponse          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Products      []*ProductDTO          `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListProductsResponse) GetProducts() []*ProductDTO {
	if x != nil {
		return x.Products
	}
	return nil
}

// 查询单个商品请求
type ProductQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品 ID
	GoodsId       string `protobuf:"bytes,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductQueryRequest) Reset() {
	*x = ProductQueryRequest{}
	mi := &file_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductQueryRequest) ProtoMessage() {}

func (x *ProductQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductQueryRequest.ProtoReflect.Descriptor instead.
func (*ProductQueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductQueryRequest) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

// 查询单个商品响应
type ProductQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductDTO            `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductQueryResponse) Reset() {
	*x = ProductQueryResponse{}
	mi := &file_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductQueryResponse) ProtoMessage() {}

func (x *ProductQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductQueryResponse.ProtoReflect.Descriptor instead.
func (*ProductQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductQueryResponse) GetProduct() *ProductDTO {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_v1_product_proto protoreflect.FileDescriptor

const file_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x10v1/product.proto\x1a\x1cgoogle/api/annotations.proto\x1a\rv1/page.proto\"\xa6\x03\n" +
	"\n" +
	"ProductDTO\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\tR\agoodsId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vgoods_title\x18\x04 \x01(\tR\n" +
	"goodsTitle\x12&\n" +
	"\x0fgoods_cover_url\x18\x05 \x01(\tR\rgoodsCoverUrl\x12*\n" +
	"\x11goods_price_range\x18\x06 \x01(\tR\x0fgoodsPriceRange\x12\x1f\n" +
	"\vgoods_price\x18\a \x01(\x01R\n" +
	"goodsPrice\x12\x1b\n" +
	"\tcos_ratio\x18\b \x01(\tR\bcosRatio\x12)\n" +
	"\x10commission_price\x18\t \x01(\tR\x0fcommissionPrice\x12\x1b\n" +
	"\tshop_name\x18\n" +
	" \x01(\tR\bshopName\x12\x1d\n" +
	"\n" +
	"brand_name\x18\v \x01(\tR\tbrandName\x12%\n" +
	"\x0ecategory_names\x18\f \x01(\tR\rcategoryNames\"\x91\x01\n" +
	"\x13ListProductsRequest\x12 \n" +
	"\x04page\x18\x01 \x01(\v2\f.PageRequestR\x04page\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12)\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\n" +
	".SortOrderR\tsortOrder\"b\n" +
	"\x14ListProductsResponse\x12!\n" +
	"\x04page\x18\x01 \x01(\v2\r.PageResponseR\x04page\x12'\n" +
	"\bproducts\x18\x02 \x03(\v2\v.ProductDTOR\bproducts\"0\n" +
	"\x13ProductQueryRequest\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\tR\agoodsId\"=\n" +
	"\x14ProductQueryResponse\x12%\n" +
	"\aproduct\x18\x01 \x01(\v2\v.ProductDTOR\aproduct2\xc6\x01\n" +
	"\x0eProductService\x12Y\n" +
	"\fListProducts\x12\x14.ListProductsRequest\x1a\x15.ListProductsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/products/list\x12Y\n" +
	"\n" +
	"GetProduct\x12\x14.ProductQueryRequest\x1a\x15.ProductQueryResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/products/detailB\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_product_proto_rawDescOnce sync.Once
	file_v1_product_proto_rawDescData []byte
)

func file_v1_product_proto_rawDescGZIP() []byte {
	file_v1_product_proto_rawDescOnce.Do(func() {
		file_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_product_proto_rawDesc), len(file_v1_product_proto_rawDesc)))
	})
	return file_v1_product_proto_rawDescData
}

var file_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_product_proto_goTypes = []any{
	(*ProductDTO)(nil),           // 0: ProductDTO
	(*ListProductsRequest)(nil),  // 1: ListProductsRequest
	(*ListProductsResponse)(nil), // 2: ListProductsResponse
	(*ProductQueryRequest)(nil),  // 3: ProductQueryRequest
	(*ProductQueryResponse)(nil), // 4: ProductQueryResponse
	(*PageRequest)(nil),          // 5: PageRequest
	(SortOrder)(0),               // 6: SortOrder
	(*PageResponse)(nil),         // 7: PageResponse
}
var file_v1_product_proto_depIdxs = []int32{
	5, // 0: ListProductsRequest.page:type_name -> PageRequest
	6, // 1: ListProductsRequest.sort_order:type_name -> SortOrder
	7, // 2: ListProductsResponse.page:type_name -> PageResponse
	0, // 3: ListProductsResponse.products:type_name -> ProductDTO
	0, // 4: ProductQueryResponse.product:type_name -> ProductDTO
	1, // 5: ProductService.ListProducts:input_type -> ListProductsRequest
	3, // 6: ProductService.GetProduct:input_type -> ProductQueryRequest
	2, // 7: ProductService.ListProducts:output_type -> ListProductsResponse
	4, // 8: ProductService.GetProduct:output_type -> ProductQueryResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_product_proto_init() }
func file_v1_product_proto_init() {
	if File_v1_product_proto != nil {
		return
	}
	file_v1_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_product_proto_rawDesc), len(file_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_product_proto_goTypes,
		DependencyIndexes: file_v1_product_proto_depIdxs,
		MessageInfos:      file_v1_product_proto_msgTypes,
	}.Build()
	File_v1_product_proto = out.File
	file_v1_product_proto_goTypes = nil
	file_v1_product_proto_depIdxs = nil
}
