// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/source_data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 原始数据条目
type SourceData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderName  string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	RawContent    string                 `protobuf:"bytes,4,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"` // 存储原始的JSON字符串
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	EntityId      string                 `protobuf:"bytes,7,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Date          string                 `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	ProcessingLog string                 `protobuf:"bytes,9,opt,name=processing_log,json=processingLog,proto3" json:"processing_log,omitempty"` // 存储ETL处理过程中的错误信息
	Retries       int32                  `protobuf:"varint,10,opt,name=retries,proto3" json:"retries,omitempty"`                                // 重试次数
	// --- 新增的请求上下文元数据 ---
	RequestMethod  string `protobuf:"bytes,11,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"` // "GET", "POST", etc.
	RequestUrl     string `protobuf:"bytes,12,opt,name=request_url,json=requestUrl,proto3" json:"request_url,omitempty"`
	RequestParams  string `protobuf:"bytes,13,opt,name=request_params,json=requestParams,proto3" json:"request_params,omitempty"`    // 存储 Query 或 Body 的 JSON 字符串
	RequestHeaders string `protobuf:"bytes,14,opt,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty"` // 存储请求头的 JSON 字符串
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SourceData) Reset() {
	*x = SourceData{}
	mi := &file_v1_source_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceData) ProtoMessage() {}

func (x *SourceData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_source_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceData.ProtoReflect.Descriptor instead.
func (*SourceData) Descriptor() ([]byte, []int) {
	return file_v1_source_data_proto_rawDescGZIP(), []int{0}
}

func (x *SourceData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SourceData) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SourceData) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *SourceData) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *SourceData) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *SourceData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SourceData) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SourceData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SourceData) GetProcessingLog() string {
	if x != nil {
		return x.ProcessingLog
	}
	return ""
}

func (x *SourceData) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *SourceData) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *SourceData) GetRequestUrl() string {
	if x != nil {
		return x.RequestUrl
	}
	return ""
}

func (x *SourceData) GetRequestParams() string {
	if x != nil {
		return x.RequestParams
	}
	return ""
}

func (x *SourceData) GetRequestHeaders() string {
	if x != nil {
		return x.RequestHeaders
	}
	return ""
}

var File_v1_source_data_proto protoreflect.FileDescriptor

const file_v1_source_data_proto_rawDesc = "" +
	"\n" +
	"\x14v1/source_data.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x03\n" +
	"\n" +
	"SourceData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x1f\n" +
	"\vraw_content\x18\x04 \x01(\tR\n" +
	"rawContent\x129\n" +
	"\n" +
	"fetched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1b\n" +
	"\tentity_id\x18\a \x01(\tR\bentityId\x12\x12\n" +
	"\x04date\x18\b \x01(\tR\x04date\x12%\n" +
	"\x0eprocessing_log\x18\t \x01(\tR\rprocessingLog\x12\x18\n" +
	"\aretries\x18\n" +
	" \x01(\x05R\aretries\x12%\n" +
	"\x0erequest_method\x18\v \x01(\tR\rrequestMethod\x12\x1f\n" +
	"\vrequest_url\x18\f \x01(\tR\n" +
	"requestUrl\x12%\n" +
	"\x0erequest_params\x18\r \x01(\tR\rrequestParams\x12'\n" +
	"\x0frequest_headers\x18\x0e \x01(\tR\x0erequestHeadersB\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_source_data_proto_rawDescOnce sync.Once
	file_v1_source_data_proto_rawDescData []byte
)

func file_v1_source_data_proto_rawDescGZIP() []byte {
	file_v1_source_data_proto_rawDescOnce.Do(func() {
		file_v1_source_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_source_data_proto_rawDesc), len(file_v1_source_data_proto_rawDesc)))
	})
	return file_v1_source_data_proto_rawDescData
}

var file_v1_source_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_source_data_proto_goTypes = []any{
	(*SourceData)(nil),            // 0: SourceData
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_v1_source_data_proto_depIdxs = []int32{
	1, // 0: SourceData.fetched_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_source_data_proto_init() }
func file_v1_source_data_proto_init() {
	if File_v1_source_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_source_data_proto_rawDesc), len(file_v1_source_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_source_data_proto_goTypes,
		DependencyIndexes: file_v1_source_data_proto_depIdxs,
		MessageInfos:      file_v1_source_data_proto_msgTypes,
	}.Build()
	File_v1_source_data_proto = out.File
	file_v1_source_data_proto_goTypes = nil
	file_v1_source_data_proto_depIdxs = nil
}
