// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/task.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 数据源提供商
type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_FEIGUA               Provider = 1 // 飞瓜
	Provider_CHANMAMA             Provider = 2 // 蝉妈妈
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "FEIGUA",
		2: "CHANMAMA",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"FEIGUA":               1,
		"CHANMAMA":             2,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_v1_task_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_proto_rawDescGZIP(), []int{0}
}

// 采集任务
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Provider      Provider               `protobuf:"varint,2,opt,name=provider,proto3,enum=Provider" json:"provider,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // e.g., "video_rank_daily", "product_detail"
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                   // JSON string for extra params like {"date": "20250714"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *Task) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Task) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_v1_task_proto protoreflect.FileDescriptor

const file_v1_task_proto_rawDesc = "" +
	"\n" +
	"\rv1/task.proto\"}\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\bprovider\x18\x02 \x01(\x0e2\t.ProviderR\bprovider\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload*>\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06FEIGUA\x10\x01\x12\f\n" +
	"\bCHANMAMA\x10\x02B\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_task_proto_rawDescOnce sync.Once
	file_v1_task_proto_rawDescData []byte
)

func file_v1_task_proto_rawDescGZIP() []byte {
	file_v1_task_proto_rawDescOnce.Do(func() {
		file_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_task_proto_rawDesc), len(file_v1_task_proto_rawDesc)))
	})
	return file_v1_task_proto_rawDescData
}

var file_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_task_proto_goTypes = []any{
	(Provider)(0), // 0: Provider
	(*Task)(nil),  // 1: Task
}
var file_v1_task_proto_depIdxs = []int32{
	0, // 0: Task.provider:type_name -> Provider
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_task_proto_init() }
func file_v1_task_proto_init() {
	if File_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_task_proto_rawDesc), len(file_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_task_proto_goTypes,
		DependencyIndexes: file_v1_task_proto_depIdxs,
		EnumInfos:         file_v1_task_proto_enumTypes,
		MessageInfos:      file_v1_task_proto_msgTypes,
	}.Build()
	File_v1_task_proto = out.File
	file_v1_task_proto_goTypes = nil
	file_v1_task_proto_depIdxs = nil
}
