// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/video_summary.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 视频总览数据 DTO
type VideoSummaryDTO struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PlayCountStr       string                 `protobuf:"bytes,1,opt,name=play_count_str,json=playCountStr,proto3" json:"play_count_str,omitempty"`
	LikeCountStr       string                 `protobuf:"bytes,2,opt,name=like_count_str,json=likeCountStr,proto3" json:"like_count_str,omitempty"`
	CommentCountStr    string                 `protobuf:"bytes,3,opt,name=comment_count_str,json=commentCountStr,proto3" json:"comment_count_str,omitempty"`
	ShareCountStr      string                 `protobuf:"bytes,4,opt,name=share_count_str,json=shareCountStr,proto3" json:"share_count_str,omitempty"`
	CollectCountStr    string                 `protobuf:"bytes,5,opt,name=collect_count_str,json=collectCountStr,proto3" json:"collect_count_str,omitempty"`
	InteractionRateStr string                 `protobuf:"bytes,6,opt,name=interaction_rate_str,json=interactionRateStr,proto3" json:"interaction_rate_str,omitempty"`
	Score              string                 `protobuf:"bytes,7,opt,name=score,proto3" json:"score,omitempty"`
	LikeCommentRateStr string                 `protobuf:"bytes,8,opt,name=like_comment_rate_str,json=likeCommentRateStr,proto3" json:"like_comment_rate_str,omitempty"`
	SalesGmvStr        string                 `protobuf:"bytes,9,opt,name=sales_gmv_str,json=salesGmvStr,proto3" json:"sales_gmv_str,omitempty"`
	SalesCountStr      string                 `protobuf:"bytes,10,opt,name=sales_count_str,json=salesCountStr,proto3" json:"sales_count_str,omitempty"`
	GoodsCountStr      string                 `protobuf:"bytes,11,opt,name=goods_count_str,json=goodsCountStr,proto3" json:"goods_count_str,omitempty"`
	Gpm                string                 `protobuf:"bytes,12,opt,name=gpm,proto3" json:"gpm,omitempty"`
	AwemeType          int32                  `protobuf:"varint,13,opt,name=aweme_type,json=awemeType,proto3" json:"aweme_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VideoSummaryDTO) Reset() {
	*x = VideoSummaryDTO{}
	mi := &file_v1_video_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSummaryDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSummaryDTO) ProtoMessage() {}

func (x *VideoSummaryDTO) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSummaryDTO.ProtoReflect.Descriptor instead.
func (*VideoSummaryDTO) Descriptor() ([]byte, []int) {
	return file_v1_video_summary_proto_rawDescGZIP(), []int{0}
}

func (x *VideoSummaryDTO) GetPlayCountStr() string {
	if x != nil {
		return x.PlayCountStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetLikeCountStr() string {
	if x != nil {
		return x.LikeCountStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetCommentCountStr() string {
	if x != nil {
		return x.CommentCountStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetShareCountStr() string {
	if x != nil {
		return x.ShareCountStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetCollectCountStr() string {
	if x != nil {
		return x.CollectCountStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetInteractionRateStr() string {
	if x != nil {
		return x.InteractionRateStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *VideoSummaryDTO) GetLikeCommentRateStr() string {
	if x != nil {
		return x.LikeCommentRateStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetSalesGmvStr() string {
	if x != nil {
		return x.SalesGmvStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetSalesCountStr() string {
	if x != nil {
		return x.SalesCountStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetGoodsCountStr() string {
	if x != nil {
		return x.GoodsCountStr
	}
	return ""
}

func (x *VideoSummaryDTO) GetGpm() string {
	if x != nil {
		return x.Gpm
	}
	return ""
}

func (x *VideoSummaryDTO) GetAwemeType() int32 {
	if x != nil {
		return x.AwemeType
	}
	return 0
}

// 飞瓜原始响应的内层 Data 结构
type FeiguaVideoSummaryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *VideoSummaryDTO       `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeiguaVideoSummaryData) Reset() {
	*x = FeiguaVideoSummaryData{}
	mi := &file_v1_video_summary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeiguaVideoSummaryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeiguaVideoSummaryData) ProtoMessage() {}

func (x *FeiguaVideoSummaryData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_summary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeiguaVideoSummaryData.ProtoReflect.Descriptor instead.
func (*FeiguaVideoSummaryData) Descriptor() ([]byte, []int) {
	return file_v1_video_summary_proto_rawDescGZIP(), []int{1}
}

func (x *FeiguaVideoSummaryData) GetData() *VideoSummaryDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_video_summary_proto protoreflect.FileDescriptor

const file_v1_video_summary_proto_rawDesc = "" +
	"\n" +
	"\x16v1/video_summary.proto\"\xfd\x03\n" +
	"\x0fVideoSummaryDTO\x12$\n" +
	"\x0eplay_count_str\x18\x01 \x01(\tR\fplayCountStr\x12$\n" +
	"\x0elike_count_str\x18\x02 \x01(\tR\flikeCountStr\x12*\n" +
	"\x11comment_count_str\x18\x03 \x01(\tR\x0fcommentCountStr\x12&\n" +
	"\x0fshare_count_str\x18\x04 \x01(\tR\rshareCountStr\x12*\n" +
	"\x11collect_count_str\x18\x05 \x01(\tR\x0fcollectCountStr\x120\n" +
	"\x14interaction_rate_str\x18\x06 \x01(\tR\x12interactionRateStr\x12\x14\n" +
	"\x05score\x18\a \x01(\tR\x05score\x121\n" +
	"\x15like_comment_rate_str\x18\b \x01(\tR\x12likeCommentRateStr\x12\"\n" +
	"\rsales_gmv_str\x18\t \x01(\tR\vsalesGmvStr\x12&\n" +
	"\x0fsales_count_str\x18\n" +
	" \x01(\tR\rsalesCountStr\x12&\n" +
	"\x0fgoods_count_str\x18\v \x01(\tR\rgoodsCountStr\x12\x10\n" +
	"\x03gpm\x18\f \x01(\tR\x03gpm\x12\x1d\n" +
	"\n" +
	"aweme_type\x18\r \x01(\x05R\tawemeType\">\n" +
	"\x16FeiguaVideoSummaryData\x12$\n" +
	"\x04Data\x18\x01 \x01(\v2\x10.VideoSummaryDTOR\x04DataB\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_video_summary_proto_rawDescOnce sync.Once
	file_v1_video_summary_proto_rawDescData []byte
)

func file_v1_video_summary_proto_rawDescGZIP() []byte {
	file_v1_video_summary_proto_rawDescOnce.Do(func() {
		file_v1_video_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_video_summary_proto_rawDesc), len(file_v1_video_summary_proto_rawDesc)))
	})
	return file_v1_video_summary_proto_rawDescData
}

var file_v1_video_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_video_summary_proto_goTypes = []any{
	(*VideoSummaryDTO)(nil),        // 0: VideoSummaryDTO
	(*FeiguaVideoSummaryData)(nil), // 1: FeiguaVideoSummaryData
}
var file_v1_video_summary_proto_depIdxs = []int32{
	0, // 0: FeiguaVideoSummaryData.Data:type_name -> VideoSummaryDTO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_video_summary_proto_init() }
func file_v1_video_summary_proto_init() {
	if File_v1_video_summary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_video_summary_proto_rawDesc), len(file_v1_video_summary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_video_summary_proto_goTypes,
		DependencyIndexes: file_v1_video_summary_proto_depIdxs,
		MessageInfos:      file_v1_video_summary_proto_msgTypes,
	}.Build()
	File_v1_video_summary_proto = out.File
	file_v1_video_summary_proto_goTypes = nil
	file_v1_video_summary_proto_depIdxs = nil
}
