// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/video_rank.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VideoRank 查询请求参数
type VideoRankQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwemeId       string                 `protobuf:"bytes,1,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`    // 视频唯一ID
	RankType      string                 `protobuf:"bytes,2,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"` // 排名类型，例如"hot", "view", "like"
	RankDate      string                 `protobuf:"bytes,3,opt,name=rank_date,json=rankDate,proto3" json:"rank_date,omitempty"` // 排名日期，格式如"2025-07-16"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRankQueryRequest) Reset() {
	*x = VideoRankQueryRequest{}
	mi := &file_v1_video_rank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRankQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRankQueryRequest) ProtoMessage() {}

func (x *VideoRankQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRankQueryRequest.ProtoReflect.Descriptor instead.
func (*VideoRankQueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{0}
}

func (x *VideoRankQueryRequest) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *VideoRankQueryRequest) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

func (x *VideoRankQueryRequest) GetRankDate() string {
	if x != nil {
		return x.RankDate
	}
	return ""
}

// VideoRank 查询响应
type VideoRankQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          *VideoRankDTO          `protobuf:"bytes,1,opt,name=rank,proto3" json:"rank,omitempty"` // 视频榜单信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRankQueryResponse) Reset() {
	*x = VideoRankQueryResponse{}
	mi := &file_v1_video_rank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRankQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRankQueryResponse) ProtoMessage() {}

func (x *VideoRankQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRankQueryResponse.ProtoReflect.Descriptor instead.
func (*VideoRankQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{1}
}

func (x *VideoRankQueryResponse) GetRank() *VideoRankDTO {
	if x != nil {
		return x.Rank
	}
	return nil
}

// 批量查询请求
type BatchVideoRankQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwemeIds      []string               `protobuf:"bytes,1,rep,name=aweme_ids,json=awemeIds,proto3" json:"aweme_ids,omitempty"` // 批量视频ID
	RankType      string                 `protobuf:"bytes,2,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"` // 排名类型
	RankDate      string                 `protobuf:"bytes,3,opt,name=rank_date,json=rankDate,proto3" json:"rank_date,omitempty"` // 排名日期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchVideoRankQueryRequest) Reset() {
	*x = BatchVideoRankQueryRequest{}
	mi := &file_v1_video_rank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchVideoRankQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchVideoRankQueryRequest) ProtoMessage() {}

func (x *BatchVideoRankQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchVideoRankQueryRequest.ProtoReflect.Descriptor instead.
func (*BatchVideoRankQueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{2}
}

func (x *BatchVideoRankQueryRequest) GetAwemeIds() []string {
	if x != nil {
		return x.AwemeIds
	}
	return nil
}

func (x *BatchVideoRankQueryRequest) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

func (x *BatchVideoRankQueryRequest) GetRankDate() string {
	if x != nil {
		return x.RankDate
	}
	return ""
}

// 批量查询响应
type BatchVideoRankQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranks         []*VideoRankDTO        `protobuf:"bytes,1,rep,name=ranks,proto3" json:"ranks,omitempty"` // 批量视频榜单信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchVideoRankQueryResponse) Reset() {
	*x = BatchVideoRankQueryResponse{}
	mi := &file_v1_video_rank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchVideoRankQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchVideoRankQueryResponse) ProtoMessage() {}

func (x *BatchVideoRankQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchVideoRankQueryResponse.ProtoReflect.Descriptor instead.
func (*BatchVideoRankQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{3}
}

func (x *BatchVideoRankQueryResponse) GetRanks() []*VideoRankDTO {
	if x != nil {
		return x.Ranks
	}
	return nil
}

// 榜单视频榜结构
type VideoRankDTO struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 榜单核心
	RankNum    int32  `protobuf:"varint,3,opt,name=rank_num,json=rankNum,proto3" json:"rank_num,omitempty"`
	PeriodType string `protobuf:"bytes,4,opt,name=period_type,json=periodType,proto3" json:"period_type,omitempty"`
	RankDate   string `protobuf:"bytes,5,opt,name=rank_date,json=rankDate,proto3" json:"rank_date,omitempty"`
	StartDate  string `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate    string `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// 视频信息
	AwemeId       string                 `protobuf:"bytes,8,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`
	AwemeCoverUrl string                 `protobuf:"bytes,9,opt,name=aweme_cover_url,json=awemeCoverUrl,proto3" json:"aweme_cover_url,omitempty"`
	AwemeDesc     string                 `protobuf:"bytes,10,opt,name=aweme_desc,json=awemeDesc,proto3" json:"aweme_desc,omitempty"`
	AwemePubTime  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=aweme_pub_time,json=awemePubTime,proto3" json:"aweme_pub_time,omitempty"`
	AwemeShareUrl string                 `protobuf:"bytes,12,opt,name=aweme_share_url,json=awemeShareUrl,proto3" json:"aweme_share_url,omitempty"`
	DurationStr   string                 `protobuf:"bytes,13,opt,name=duration_str,json=durationStr,proto3" json:"duration_str,omitempty"`
	AwemeScoreStr string                 `protobuf:"bytes,14,opt,name=aweme_score_str,json=awemeScoreStr,proto3" json:"aweme_score_str,omitempty"`
	// 商品信息
	GoodsId         string  `protobuf:"bytes,15,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsTitle      string  `protobuf:"bytes,16,opt,name=goods_title,json=goodsTitle,proto3" json:"goods_title,omitempty"`
	GoodsCoverUrl   string  `protobuf:"bytes,17,opt,name=goods_cover_url,json=goodsCoverUrl,proto3" json:"goods_cover_url,omitempty"`
	GoodsPriceRange string  `protobuf:"bytes,18,opt,name=goods_price_range,json=goodsPriceRange,proto3" json:"goods_price_range,omitempty"`
	GoodsPrice      float64 `protobuf:"fixed64,19,opt,name=goods_price,json=goodsPrice,proto3" json:"goods_price,omitempty"`
	CosRatio        string  `protobuf:"bytes,20,opt,name=cos_ratio,json=cosRatio,proto3" json:"cos_ratio,omitempty"`
	CommissionPrice string  `protobuf:"bytes,21,opt,name=commission_price,json=commissionPrice,proto3" json:"commission_price,omitempty"`
	ShopName        string  `protobuf:"bytes,22,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	BrandName       string  `protobuf:"bytes,23,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	CategoryNames   string  `protobuf:"bytes,24,opt,name=category_names,json=categoryNames,proto3" json:"category_names,omitempty"`
	// 博主信息
	BloggerId      int32  `protobuf:"varint,25,opt,name=blogger_id,json=bloggerId,proto3" json:"blogger_id,omitempty"`
	BloggerUid     string `protobuf:"bytes,26,opt,name=blogger_uid,json=bloggerUid,proto3" json:"blogger_uid,omitempty"`
	BloggerName    string `protobuf:"bytes,27,opt,name=blogger_name,json=bloggerName,proto3" json:"blogger_name,omitempty"`
	BloggerAvatar  string `protobuf:"bytes,28,opt,name=blogger_avatar,json=bloggerAvatar,proto3" json:"blogger_avatar,omitempty"`
	BloggerFansNum int32  `protobuf:"varint,29,opt,name=blogger_fans_num,json=bloggerFansNum,proto3" json:"blogger_fans_num,omitempty"`
	BloggerTag     string `protobuf:"bytes,30,opt,name=blogger_tag,json=bloggerTag,proto3" json:"blogger_tag,omitempty"`
	// 榜单统计
	SalesCountStr   string `protobuf:"bytes,31,opt,name=sales_count_str,json=salesCountStr,proto3" json:"sales_count_str,omitempty"`
	TotalSalesStr   string `protobuf:"bytes,32,opt,name=total_sales_str,json=totalSalesStr,proto3" json:"total_sales_str,omitempty"`
	LikeCountIncStr string `protobuf:"bytes,33,opt,name=like_count_inc_str,json=likeCountIncStr,proto3" json:"like_count_inc_str,omitempty"`
	PlayCountIncStr string `protobuf:"bytes,34,opt,name=play_count_inc_str,json=playCountIncStr,proto3" json:"play_count_inc_str,omitempty"`
	// 元数据
	RawJson       string `protobuf:"bytes,35,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRankDTO) Reset() {
	*x = VideoRankDTO{}
	mi := &file_v1_video_rank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRankDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRankDTO) ProtoMessage() {}

func (x *VideoRankDTO) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRankDTO.ProtoReflect.Descriptor instead.
func (*VideoRankDTO) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{4}
}

func (x *VideoRankDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoRankDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VideoRankDTO) GetRankNum() int32 {
	if x != nil {
		return x.RankNum
	}
	return 0
}

func (x *VideoRankDTO) GetPeriodType() string {
	if x != nil {
		return x.PeriodType
	}
	return ""
}

func (x *VideoRankDTO) GetRankDate() string {
	if x != nil {
		return x.RankDate
	}
	return ""
}

func (x *VideoRankDTO) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *VideoRankDTO) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *VideoRankDTO) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *VideoRankDTO) GetAwemeCoverUrl() string {
	if x != nil {
		return x.AwemeCoverUrl
	}
	return ""
}

func (x *VideoRankDTO) GetAwemeDesc() string {
	if x != nil {
		return x.AwemeDesc
	}
	return ""
}

func (x *VideoRankDTO) GetAwemePubTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AwemePubTime
	}
	return nil
}

func (x *VideoRankDTO) GetAwemeShareUrl() string {
	if x != nil {
		return x.AwemeShareUrl
	}
	return ""
}

func (x *VideoRankDTO) GetDurationStr() string {
	if x != nil {
		return x.DurationStr
	}
	return ""
}

func (x *VideoRankDTO) GetAwemeScoreStr() string {
	if x != nil {
		return x.AwemeScoreStr
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsTitle() string {
	if x != nil {
		return x.GoodsTitle
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsCoverUrl() string {
	if x != nil {
		return x.GoodsCoverUrl
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsPriceRange() string {
	if x != nil {
		return x.GoodsPriceRange
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsPrice() float64 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *VideoRankDTO) GetCosRatio() string {
	if x != nil {
		return x.CosRatio
	}
	return ""
}

func (x *VideoRankDTO) GetCommissionPrice() string {
	if x != nil {
		return x.CommissionPrice
	}
	return ""
}

func (x *VideoRankDTO) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *VideoRankDTO) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *VideoRankDTO) GetCategoryNames() string {
	if x != nil {
		return x.CategoryNames
	}
	return ""
}

func (x *VideoRankDTO) GetBloggerId() int32 {
	if x != nil {
		return x.BloggerId
	}
	return 0
}

func (x *VideoRankDTO) GetBloggerUid() string {
	if x != nil {
		return x.BloggerUid
	}
	return ""
}

func (x *VideoRankDTO) GetBloggerName() string {
	if x != nil {
		return x.BloggerName
	}
	return ""
}

func (x *VideoRankDTO) GetBloggerAvatar() string {
	if x != nil {
		return x.BloggerAvatar
	}
	return ""
}

func (x *VideoRankDTO) GetBloggerFansNum() int32 {
	if x != nil {
		return x.BloggerFansNum
	}
	return 0
}

func (x *VideoRankDTO) GetBloggerTag() string {
	if x != nil {
		return x.BloggerTag
	}
	return ""
}

func (x *VideoRankDTO) GetSalesCountStr() string {
	if x != nil {
		return x.SalesCountStr
	}
	return ""
}

func (x *VideoRankDTO) GetTotalSalesStr() string {
	if x != nil {
		return x.TotalSalesStr
	}
	return ""
}

func (x *VideoRankDTO) GetLikeCountIncStr() string {
	if x != nil {
		return x.LikeCountIncStr
	}
	return ""
}

func (x *VideoRankDTO) GetPlayCountIncStr() string {
	if x != nil {
		return x.PlayCountIncStr
	}
	return ""
}

func (x *VideoRankDTO) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

var File_v1_video_rank_proto protoreflect.FileDescriptor

const file_v1_video_rank_proto_rawDesc = "" +
	"\n" +
	"\x13v1/video_rank.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"l\n" +
	"\x15VideoRankQueryRequest\x12\x19\n" +
	"\baweme_id\x18\x01 \x01(\tR\aawemeId\x12\x1b\n" +
	"\trank_type\x18\x02 \x01(\tR\brankType\x12\x1b\n" +
	"\trank_date\x18\x03 \x01(\tR\brankDate\";\n" +
	"\x16VideoRankQueryResponse\x12!\n" +
	"\x04rank\x18\x01 \x01(\v2\r.VideoRankDTOR\x04rank\"s\n" +
	"\x1aBatchVideoRankQueryRequest\x12\x1b\n" +
	"\taweme_ids\x18\x01 \x03(\tR\bawemeIds\x12\x1b\n" +
	"\trank_type\x18\x02 \x01(\tR\brankType\x12\x1b\n" +
	"\trank_date\x18\x03 \x01(\tR\brankDate\"B\n" +
	"\x1bBatchVideoRankQueryResponse\x12#\n" +
	"\x05ranks\x18\x01 \x03(\v2\r.VideoRankDTOR\x05ranks\"\xf9\t\n" +
	"\fVideoRankDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\brank_num\x18\x03 \x01(\x05R\arankNum\x12\x1f\n" +
	"\vperiod_type\x18\x04 \x01(\tR\n" +
	"periodType\x12\x1b\n" +
	"\trank_date\x18\x05 \x01(\tR\brankDate\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\x19\n" +
	"\baweme_id\x18\b \x01(\tR\aawemeId\x12&\n" +
	"\x0faweme_cover_url\x18\t \x01(\tR\rawemeCoverUrl\x12\x1d\n" +
	"\n" +
	"aweme_desc\x18\n" +
	" \x01(\tR\tawemeDesc\x12@\n" +
	"\x0eaweme_pub_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\fawemePubTime\x12&\n" +
	"\x0faweme_share_url\x18\f \x01(\tR\rawemeShareUrl\x12!\n" +
	"\fduration_str\x18\r \x01(\tR\vdurationStr\x12&\n" +
	"\x0faweme_score_str\x18\x0e \x01(\tR\rawemeScoreStr\x12\x19\n" +
	"\bgoods_id\x18\x0f \x01(\tR\agoodsId\x12\x1f\n" +
	"\vgoods_title\x18\x10 \x01(\tR\n" +
	"goodsTitle\x12&\n" +
	"\x0fgoods_cover_url\x18\x11 \x01(\tR\rgoodsCoverUrl\x12*\n" +
	"\x11goods_price_range\x18\x12 \x01(\tR\x0fgoodsPriceRange\x12\x1f\n" +
	"\vgoods_price\x18\x13 \x01(\x01R\n" +
	"goodsPrice\x12\x1b\n" +
	"\tcos_ratio\x18\x14 \x01(\tR\bcosRatio\x12)\n" +
	"\x10commission_price\x18\x15 \x01(\tR\x0fcommissionPrice\x12\x1b\n" +
	"\tshop_name\x18\x16 \x01(\tR\bshopName\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x17 \x01(\tR\tbrandName\x12%\n" +
	"\x0ecategory_names\x18\x18 \x01(\tR\rcategoryNames\x12\x1d\n" +
	"\n" +
	"blogger_id\x18\x19 \x01(\x05R\tbloggerId\x12\x1f\n" +
	"\vblogger_uid\x18\x1a \x01(\tR\n" +
	"bloggerUid\x12!\n" +
	"\fblogger_name\x18\x1b \x01(\tR\vbloggerName\x12%\n" +
	"\x0eblogger_avatar\x18\x1c \x01(\tR\rbloggerAvatar\x12(\n" +
	"\x10blogger_fans_num\x18\x1d \x01(\x05R\x0ebloggerFansNum\x12\x1f\n" +
	"\vblogger_tag\x18\x1e \x01(\tR\n" +
	"bloggerTag\x12&\n" +
	"\x0fsales_count_str\x18\x1f \x01(\tR\rsalesCountStr\x12&\n" +
	"\x0ftotal_sales_str\x18  \x01(\tR\rtotalSalesStr\x12+\n" +
	"\x12like_count_inc_str\x18! \x01(\tR\x0flikeCountIncStr\x12+\n" +
	"\x12play_count_inc_str\x18\" \x01(\tR\x0fplayCountIncStr\x12\x19\n" +
	"\braw_json\x18# \x01(\tR\arawJson2\xd1\x01\n" +
	"\tVideoRank\x12W\n" +
	"\fGetVideoRank\x12\x16.VideoRankQueryRequest\x1a\x17.VideoRankQueryResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/video_rank\x12k\n" +
	"\x11BatchGetVideoRank\x12\x1b.BatchVideoRankQueryRequest\x1a\x1c.BatchVideoRankQueryResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/video_rank/ListB\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_video_rank_proto_rawDescOnce sync.Once
	file_v1_video_rank_proto_rawDescData []byte
)

func file_v1_video_rank_proto_rawDescGZIP() []byte {
	file_v1_video_rank_proto_rawDescOnce.Do(func() {
		file_v1_video_rank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_video_rank_proto_rawDesc), len(file_v1_video_rank_proto_rawDesc)))
	})
	return file_v1_video_rank_proto_rawDescData
}

var file_v1_video_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_video_rank_proto_goTypes = []any{
	(*VideoRankQueryRequest)(nil),       // 0: VideoRankQueryRequest
	(*VideoRankQueryResponse)(nil),      // 1: VideoRankQueryResponse
	(*BatchVideoRankQueryRequest)(nil),  // 2: BatchVideoRankQueryRequest
	(*BatchVideoRankQueryResponse)(nil), // 3: BatchVideoRankQueryResponse
	(*VideoRankDTO)(nil),                // 4: VideoRankDTO
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_v1_video_rank_proto_depIdxs = []int32{
	4, // 0: VideoRankQueryResponse.rank:type_name -> VideoRankDTO
	4, // 1: BatchVideoRankQueryResponse.ranks:type_name -> VideoRankDTO
	5, // 2: VideoRankDTO.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: VideoRankDTO.aweme_pub_time:type_name -> google.protobuf.Timestamp
	0, // 4: VideoRank.GetVideoRank:input_type -> VideoRankQueryRequest
	2, // 5: VideoRank.BatchGetVideoRank:input_type -> BatchVideoRankQueryRequest
	1, // 6: VideoRank.GetVideoRank:output_type -> VideoRankQueryResponse
	3, // 7: VideoRank.BatchGetVideoRank:output_type -> BatchVideoRankQueryResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_video_rank_proto_init() }
func file_v1_video_rank_proto_init() {
	if File_v1_video_rank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_video_rank_proto_rawDesc), len(file_v1_video_rank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_video_rank_proto_goTypes,
		DependencyIndexes: file_v1_video_rank_proto_depIdxs,
		MessageInfos:      file_v1_video_rank_proto_msgTypes,
	}.Build()
	File_v1_video_rank_proto = out.File
	file_v1_video_rank_proto_goTypes = nil
	file_v1_video_rank_proto_depIdxs = nil
}
