// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/video.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 视频维度数据 DTO
type VideoDTO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键ID
	AwemeId string `protobuf:"bytes,1,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt string `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 视频描述
	AwemeDesc string `protobuf:"bytes,4,opt,name=aweme_desc,json=awemeDesc,proto3" json:"aweme_desc,omitempty"`
	// 视频封面URL
	AwemeCoverUrl string `protobuf:"bytes,5,opt,name=aweme_cover_url,json=awemeCoverUrl,proto3" json:"aweme_cover_url,omitempty"`
	// 视频发布时间
	AwemePubTime string `protobuf:"bytes,6,opt,name=aweme_pub_time,json=awemePubTime,proto3" json:"aweme_pub_time,omitempty"`
	// 视频分享URL
	AwemeShareUrl string `protobuf:"bytes,39,opt,name=aweme_share_url,json=awemeShareUrl,proto3" json:"aweme_share_url,omitempty"`
	// 视频详情URL
	AwemeDetailUrl string `protobuf:"bytes,40,opt,name=aweme_detail_url,json=awemeDetailUrl,proto3" json:"aweme_detail_url,omitempty"`
	// 博主ID
	BloggerId int64 `protobuf:"varint,7,opt,name=blogger_id,json=bloggerId,proto3" json:"blogger_id,omitempty"`
	// 播放量字符串
	PlayCountStr string `protobuf:"bytes,8,opt,name=play_count_str,json=playCountStr,proto3" json:"play_count_str,omitempty"`
	// 点赞量字符串
	LikeCountStr string `protobuf:"bytes,9,opt,name=like_count_str,json=likeCountStr,proto3" json:"like_count_str,omitempty"`
	// 评论量字符串
	CommentCountStr string `protobuf:"bytes,10,opt,name=comment_count_str,json=commentCountStr,proto3" json:"comment_count_str,omitempty"`
	// 分享量字符串
	ShareCountStr string `protobuf:"bytes,11,opt,name=share_count_str,json=shareCountStr,proto3" json:"share_count_str,omitempty"`
	// 收藏量字符串
	CollectCountStr string `protobuf:"bytes,12,opt,name=collect_count_str,json=collectCountStr,proto3" json:"collect_count_str,omitempty"`
	// 互动率字符串
	InteractionRateStr string `protobuf:"bytes,13,opt,name=interaction_rate_str,json=interactionRateStr,proto3" json:"interaction_rate_str,omitempty"`
	// 分数字符串
	ScoreStr string `protobuf:"bytes,14,opt,name=score_str,json=scoreStr,proto3" json:"score_str,omitempty"`
	// 点赞评论率字符串
	LikeCommentRateStr string `protobuf:"bytes,15,opt,name=like_comment_rate_str,json=likeCommentRateStr,proto3" json:"like_comment_rate_str,omitempty"`
	// 销售GMV字符串
	SalesGmvStr string `protobuf:"bytes,16,opt,name=sales_gmv_str,json=salesGmvStr,proto3" json:"sales_gmv_str,omitempty"`
	// 销售量字符串
	SalesCountStr string `protobuf:"bytes,17,opt,name=sales_count_str,json=salesCountStr,proto3" json:"sales_count_str,omitempty"`
	// 商品量字符串
	GoodsCountStr string `protobuf:"bytes,18,opt,name=goods_count_str,json=goodsCountStr,proto3" json:"goods_count_str,omitempty"`
	// 商品数字符串
	GpmStr string `protobuf:"bytes,19,opt,name=gpm_str,json=gpmStr,proto3" json:"gpm_str,omitempty"`
	// 视频类型
	AwemeType int32 `protobuf:"varint,20,opt,name=aweme_type,json=awemeType,proto3" json:"aweme_type,omitempty"`
	// 汇总更新时间
	SummaryUpdatedAt string `protobuf:"bytes,21,opt,name=summary_updated_at,json=summaryUpdatedAt,proto3" json:"summary_updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VideoDTO) Reset() {
	*x = VideoDTO{}
	mi := &file_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoDTO) ProtoMessage() {}

func (x *VideoDTO) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoDTO.ProtoReflect.Descriptor instead.
func (*VideoDTO) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *VideoDTO) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *VideoDTO) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoDTO) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VideoDTO) GetAwemeDesc() string {
	if x != nil {
		return x.AwemeDesc
	}
	return ""
}

func (x *VideoDTO) GetAwemeCoverUrl() string {
	if x != nil {
		return x.AwemeCoverUrl
	}
	return ""
}

func (x *VideoDTO) GetAwemePubTime() string {
	if x != nil {
		return x.AwemePubTime
	}
	return ""
}

func (x *VideoDTO) GetAwemeShareUrl() string {
	if x != nil {
		return x.AwemeShareUrl
	}
	return ""
}

func (x *VideoDTO) GetAwemeDetailUrl() string {
	if x != nil {
		return x.AwemeDetailUrl
	}
	return ""
}

func (x *VideoDTO) GetBloggerId() int64 {
	if x != nil {
		return x.BloggerId
	}
	return 0
}

func (x *VideoDTO) GetPlayCountStr() string {
	if x != nil {
		return x.PlayCountStr
	}
	return ""
}

func (x *VideoDTO) GetLikeCountStr() string {
	if x != nil {
		return x.LikeCountStr
	}
	return ""
}

func (x *VideoDTO) GetCommentCountStr() string {
	if x != nil {
		return x.CommentCountStr
	}
	return ""
}

func (x *VideoDTO) GetShareCountStr() string {
	if x != nil {
		return x.ShareCountStr
	}
	return ""
}

func (x *VideoDTO) GetCollectCountStr() string {
	if x != nil {
		return x.CollectCountStr
	}
	return ""
}

func (x *VideoDTO) GetInteractionRateStr() string {
	if x != nil {
		return x.InteractionRateStr
	}
	return ""
}

func (x *VideoDTO) GetScoreStr() string {
	if x != nil {
		return x.ScoreStr
	}
	return ""
}

func (x *VideoDTO) GetLikeCommentRateStr() string {
	if x != nil {
		return x.LikeCommentRateStr
	}
	return ""
}

func (x *VideoDTO) GetSalesGmvStr() string {
	if x != nil {
		return x.SalesGmvStr
	}
	return ""
}

func (x *VideoDTO) GetSalesCountStr() string {
	if x != nil {
		return x.SalesCountStr
	}
	return ""
}

func (x *VideoDTO) GetGoodsCountStr() string {
	if x != nil {
		return x.GoodsCountStr
	}
	return ""
}

func (x *VideoDTO) GetGpmStr() string {
	if x != nil {
		return x.GpmStr
	}
	return ""
}

func (x *VideoDTO) GetAwemeType() int32 {
	if x != nil {
		return x.AwemeType
	}
	return 0
}

func (x *VideoDTO) GetSummaryUpdatedAt() string {
	if x != nil {
		return x.SummaryUpdatedAt
	}
	return ""
}

// 分页查询视频请求
type ListVideosRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页参数
	Page *PageRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// 模糊查询关键字 (将作用于 aweme_desc 字段)
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// 排序字段 (例如: "aweme_pub_time", "summary_updated_at")
	SortBy string `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// 排序方向（1:ASC / 2:DESC）
	SortOrder     SortOrder `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosRequest) Reset() {
	*x = ListVideosRequest{}
	mi := &file_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosRequest) ProtoMessage() {}

func (x *ListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *ListVideosRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListVideosRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListVideosRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListVideosRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_UNSORTED
}

// 分页查询视频响应
type ListVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResponse          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Videos        []*VideoDTO            `protobuf:"bytes,2,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosResponse) Reset() {
	*x = ListVideosResponse{}
	mi := &file_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosResponse) ProtoMessage() {}

func (x *ListVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosResponse.ProtoReflect.Descriptor instead.
func (*ListVideosResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{2}
}

func (x *ListVideosResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListVideosResponse) GetVideos() []*VideoDTO {
	if x != nil {
		return x.Videos
	}
	return nil
}

// 查询单个视频信息请求
type VideoQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwemeId       string                 `protobuf:"bytes,1,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoQueryRequest) Reset() {
	*x = VideoQueryRequest{}
	mi := &file_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoQueryRequest) ProtoMessage() {}

func (x *VideoQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoQueryRequest.ProtoReflect.Descriptor instead.
func (*VideoQueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{3}
}

func (x *VideoQueryRequest) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

// 查询单个视频信息响应
type VideoQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *VideoDTO              `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoQueryResponse) Reset() {
	*x = VideoQueryResponse{}
	mi := &file_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoQueryResponse) ProtoMessage() {}

func (x *VideoQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoQueryResponse.ProtoReflect.Descriptor instead.
func (*VideoQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *VideoQueryResponse) GetVideo() *VideoDTO {
	if x != nil {
		return x.Video
	}
	return nil
}

var File_v1_video_proto protoreflect.FileDescriptor

const file_v1_video_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/video.proto\x1a\x1cgoogle/api/annotations.proto\x1a\rv1/page.proto\"\xe9\x06\n" +
	"\bVideoDTO\x12\x19\n" +
	"\baweme_id\x18\x01 \x01(\tR\aawemeId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"aweme_desc\x18\x04 \x01(\tR\tawemeDesc\x12&\n" +
	"\x0faweme_cover_url\x18\x05 \x01(\tR\rawemeCoverUrl\x12$\n" +
	"\x0eaweme_pub_time\x18\x06 \x01(\tR\fawemePubTime\x12&\n" +
	"\x0faweme_share_url\x18' \x01(\tR\rawemeShareUrl\x12(\n" +
	"\x10aweme_detail_url\x18( \x01(\tR\x0eawemeDetailUrl\x12\x1d\n" +
	"\n" +
	"blogger_id\x18\a \x01(\x03R\tbloggerId\x12$\n" +
	"\x0eplay_count_str\x18\b \x01(\tR\fplayCountStr\x12$\n" +
	"\x0elike_count_str\x18\t \x01(\tR\flikeCountStr\x12*\n" +
	"\x11comment_count_str\x18\n" +
	" \x01(\tR\x0fcommentCountStr\x12&\n" +
	"\x0fshare_count_str\x18\v \x01(\tR\rshareCountStr\x12*\n" +
	"\x11collect_count_str\x18\f \x01(\tR\x0fcollectCountStr\x120\n" +
	"\x14interaction_rate_str\x18\r \x01(\tR\x12interactionRateStr\x12\x1b\n" +
	"\tscore_str\x18\x0e \x01(\tR\bscoreStr\x121\n" +
	"\x15like_comment_rate_str\x18\x0f \x01(\tR\x12likeCommentRateStr\x12\"\n" +
	"\rsales_gmv_str\x18\x10 \x01(\tR\vsalesGmvStr\x12&\n" +
	"\x0fsales_count_str\x18\x11 \x01(\tR\rsalesCountStr\x12&\n" +
	"\x0fgoods_count_str\x18\x12 \x01(\tR\rgoodsCountStr\x12\x17\n" +
	"\agpm_str\x18\x13 \x01(\tR\x06gpmStr\x12\x1d\n" +
	"\n" +
	"aweme_type\x18\x14 \x01(\x05R\tawemeType\x12,\n" +
	"\x12summary_updated_at\x18\x15 \x01(\tR\x10summaryUpdatedAt\"\x8f\x01\n" +
	"\x11ListVideosRequest\x12 \n" +
	"\x04page\x18\x01 \x01(\v2\f.PageRequestR\x04page\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12)\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\n" +
	".SortOrderR\tsortOrder\"Z\n" +
	"\x12ListVideosResponse\x12!\n" +
	"\x04page\x18\x01 \x01(\v2\r.PageResponseR\x04page\x12!\n" +
	"\x06videos\x18\x02 \x03(\v2\t.VideoDTOR\x06videos\".\n" +
	"\x11VideoQueryRequest\x12\x19\n" +
	"\baweme_id\x18\x01 \x01(\tR\aawemeId\"5\n" +
	"\x12VideoQueryResponse\x12\x1f\n" +
	"\x05video\x18\x01 \x01(\v2\t.VideoDTOR\x05video2\xb4\x01\n" +
	"\fVideoService\x12Q\n" +
	"\n" +
	"ListVideos\x12\x12.ListVideosRequest\x1a\x13.ListVideosResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/videos/list\x12Q\n" +
	"\bGetVideo\x12\x12.VideoQueryRequest\x1a\x13.VideoQueryResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/videos/detailB\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_video_proto_rawDescOnce sync.Once
	file_v1_video_proto_rawDescData []byte
)

func file_v1_video_proto_rawDescGZIP() []byte {
	file_v1_video_proto_rawDescOnce.Do(func() {
		file_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_video_proto_rawDesc), len(file_v1_video_proto_rawDesc)))
	})
	return file_v1_video_proto_rawDescData
}

var file_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_video_proto_goTypes = []any{
	(*VideoDTO)(nil),           // 0: VideoDTO
	(*ListVideosRequest)(nil),  // 1: ListVideosRequest
	(*ListVideosResponse)(nil), // 2: ListVideosResponse
	(*VideoQueryRequest)(nil),  // 3: VideoQueryRequest
	(*VideoQueryResponse)(nil), // 4: VideoQueryResponse
	(*PageRequest)(nil),        // 5: PageRequest
	(SortOrder)(0),             // 6: SortOrder
	(*PageResponse)(nil),       // 7: PageResponse
}
var file_v1_video_proto_depIdxs = []int32{
	5, // 0: ListVideosRequest.page:type_name -> PageRequest
	6, // 1: ListVideosRequest.sort_order:type_name -> SortOrder
	7, // 2: ListVideosResponse.page:type_name -> PageResponse
	0, // 3: ListVideosResponse.videos:type_name -> VideoDTO
	0, // 4: VideoQueryResponse.video:type_name -> VideoDTO
	1, // 5: VideoService.ListVideos:input_type -> ListVideosRequest
	3, // 6: VideoService.GetVideo:input_type -> VideoQueryRequest
	2, // 7: VideoService.ListVideos:output_type -> ListVideosResponse
	4, // 8: VideoService.GetVideo:output_type -> VideoQueryResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_video_proto_init() }
func file_v1_video_proto_init() {
	if File_v1_video_proto != nil {
		return
	}
	file_v1_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_video_proto_rawDesc), len(file_v1_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_video_proto_goTypes,
		DependencyIndexes: file_v1_video_proto_depIdxs,
		MessageInfos:      file_v1_video_proto_msgTypes,
	}.Build()
	File_v1_video_proto = out.File
	file_v1_video_proto_goTypes = nil
	file_v1_video_proto_depIdxs = nil
}
