// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/video_trend.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 视频每日趋势数据 DTO
type VideoTrendDTO struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 视频ID
	AwemeId string `protobuf:"bytes,4,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`
	// 日期代码
	DateCode int32 `protobuf:"varint,5,opt,name=date_code,json=dateCode,proto3" json:"date_code,omitempty"`
	// 指标（同时包含原始数值和字符串）
	LikeCount          int64   `protobuf:"varint,6,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	LikeCountStr       string  `protobuf:"bytes,7,opt,name=like_count_str,json=likeCountStr,proto3" json:"like_count_str,omitempty"`
	ShareCount         int64   `protobuf:"varint,8,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	ShareCountStr      string  `protobuf:"bytes,9,opt,name=share_count_str,json=shareCountStr,proto3" json:"share_count_str,omitempty"`
	CommentCount       int64   `protobuf:"varint,10,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CommentCountStr    string  `protobuf:"bytes,11,opt,name=comment_count_str,json=commentCountStr,proto3" json:"comment_count_str,omitempty"`
	CollectCount       int64   `protobuf:"varint,12,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	CollectCountStr    string  `protobuf:"bytes,13,opt,name=collect_count_str,json=collectCountStr,proto3" json:"collect_count_str,omitempty"`
	InteractionRate    float64 `protobuf:"fixed64,14,opt,name=interaction_rate,json=interactionRate,proto3" json:"interaction_rate,omitempty"`
	InteractionRateStr string  `protobuf:"bytes,15,opt,name=interaction_rate_str,json=interactionRateStr,proto3" json:"interaction_rate_str,omitempty"`
	IncLikeCount       int64   `protobuf:"varint,16,opt,name=inc_like_count,json=incLikeCount,proto3" json:"inc_like_count,omitempty"`
	IncLikeCountStr    string  `protobuf:"bytes,17,opt,name=inc_like_count_str,json=incLikeCountStr,proto3" json:"inc_like_count_str,omitempty"`
	IncShareCount      int64   `protobuf:"varint,18,opt,name=inc_share_count,json=incShareCount,proto3" json:"inc_share_count,omitempty"`
	IncShareCountStr   string  `protobuf:"bytes,19,opt,name=inc_share_count_str,json=incShareCountStr,proto3" json:"inc_share_count_str,omitempty"`
	IncCommentCount    int64   `protobuf:"varint,20,opt,name=inc_comment_count,json=incCommentCount,proto3" json:"inc_comment_count,omitempty"`
	IncCommentCountStr string  `protobuf:"bytes,21,opt,name=inc_comment_count_str,json=incCommentCountStr,proto3" json:"inc_comment_count_str,omitempty"`
	IncCollectCount    int64   `protobuf:"varint,22,opt,name=inc_collect_count,json=incCollectCount,proto3" json:"inc_collect_count,omitempty"`
	IncCollectCountStr string  `protobuf:"bytes,23,opt,name=inc_collect_count_str,json=incCollectCountStr,proto3" json:"inc_collect_count_str,omitempty"`
	SalesCount         int64   `protobuf:"varint,24,opt,name=sales_count,json=salesCount,proto3" json:"sales_count,omitempty"`
	SalesCountStr      string  `protobuf:"bytes,25,opt,name=sales_count_str,json=salesCountStr,proto3" json:"sales_count_str,omitempty"`
	SalesGmv           float64 `protobuf:"fixed64,26,opt,name=sales_gmv,json=salesGmv,proto3" json:"sales_gmv,omitempty"`
	SalesGmvStr        string  `protobuf:"bytes,27,opt,name=sales_gmv_str,json=salesGmvStr,proto3" json:"sales_gmv_str,omitempty"`
	Fans               int64   `protobuf:"varint,28,opt,name=fans,proto3" json:"fans,omitempty"`
	FansStr            string  `protobuf:"bytes,29,opt,name=fans_str,json=fansStr,proto3" json:"fans_str,omitempty"`
	IncSalesCount      int64   `protobuf:"varint,30,opt,name=inc_sales_count,json=incSalesCount,proto3" json:"inc_sales_count,omitempty"`
	IncSalesCountStr   string  `protobuf:"bytes,31,opt,name=inc_sales_count_str,json=incSalesCountStr,proto3" json:"inc_sales_count_str,omitempty"`
	IncSalesGmv        float64 `protobuf:"fixed64,32,opt,name=inc_sales_gmv,json=incSalesGmv,proto3" json:"inc_sales_gmv,omitempty"`
	IncSalesGmvStr     string  `protobuf:"bytes,33,opt,name=inc_sales_gmv_str,json=incSalesGmvStr,proto3" json:"inc_sales_gmv_str,omitempty"`
	IncFans            int64   `protobuf:"varint,34,opt,name=inc_fans,json=incFans,proto3" json:"inc_fans,omitempty"`
	IncFansStr         string  `protobuf:"bytes,35,opt,name=inc_fans_str,json=incFansStr,proto3" json:"inc_fans_str,omitempty"`
	Gpm                float64 `protobuf:"fixed64,36,opt,name=gpm,proto3" json:"gpm,omitempty"`
	GpmStr             string  `protobuf:"bytes,37,opt,name=gpm_str,json=gpmStr,proto3" json:"gpm_str,omitempty"`
	// 列表时间
	ListTimeStr string `protobuf:"bytes,38,opt,name=list_time_str,json=listTimeStr,proto3" json:"list_time_str,omitempty"`
	// 时间戳
	TimeStamp     int64 `protobuf:"varint,39,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoTrendDTO) Reset() {
	*x = VideoTrendDTO{}
	mi := &file_v1_video_trend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTrendDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTrendDTO) ProtoMessage() {}

func (x *VideoTrendDTO) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_trend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTrendDTO.ProtoReflect.Descriptor instead.
func (*VideoTrendDTO) Descriptor() ([]byte, []int) {
	return file_v1_video_trend_proto_rawDescGZIP(), []int{0}
}

func (x *VideoTrendDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoTrendDTO) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoTrendDTO) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VideoTrendDTO) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *VideoTrendDTO) GetDateCode() int32 {
	if x != nil {
		return x.DateCode
	}
	return 0
}

func (x *VideoTrendDTO) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoTrendDTO) GetLikeCountStr() string {
	if x != nil {
		return x.LikeCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *VideoTrendDTO) GetShareCountStr() string {
	if x != nil {
		return x.ShareCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *VideoTrendDTO) GetCommentCountStr() string {
	if x != nil {
		return x.CommentCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetCollectCount() int64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *VideoTrendDTO) GetCollectCountStr() string {
	if x != nil {
		return x.CollectCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetInteractionRate() float64 {
	if x != nil {
		return x.InteractionRate
	}
	return 0
}

func (x *VideoTrendDTO) GetInteractionRateStr() string {
	if x != nil {
		return x.InteractionRateStr
	}
	return ""
}

func (x *VideoTrendDTO) GetIncLikeCount() int64 {
	if x != nil {
		return x.IncLikeCount
	}
	return 0
}

func (x *VideoTrendDTO) GetIncLikeCountStr() string {
	if x != nil {
		return x.IncLikeCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetIncShareCount() int64 {
	if x != nil {
		return x.IncShareCount
	}
	return 0
}

func (x *VideoTrendDTO) GetIncShareCountStr() string {
	if x != nil {
		return x.IncShareCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetIncCommentCount() int64 {
	if x != nil {
		return x.IncCommentCount
	}
	return 0
}

func (x *VideoTrendDTO) GetIncCommentCountStr() string {
	if x != nil {
		return x.IncCommentCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetIncCollectCount() int64 {
	if x != nil {
		return x.IncCollectCount
	}
	return 0
}

func (x *VideoTrendDTO) GetIncCollectCountStr() string {
	if x != nil {
		return x.IncCollectCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetSalesCount() int64 {
	if x != nil {
		return x.SalesCount
	}
	return 0
}

func (x *VideoTrendDTO) GetSalesCountStr() string {
	if x != nil {
		return x.SalesCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetSalesGmv() float64 {
	if x != nil {
		return x.SalesGmv
	}
	return 0
}

func (x *VideoTrendDTO) GetSalesGmvStr() string {
	if x != nil {
		return x.SalesGmvStr
	}
	return ""
}

func (x *VideoTrendDTO) GetFans() int64 {
	if x != nil {
		return x.Fans
	}
	return 0
}

func (x *VideoTrendDTO) GetFansStr() string {
	if x != nil {
		return x.FansStr
	}
	return ""
}

func (x *VideoTrendDTO) GetIncSalesCount() int64 {
	if x != nil {
		return x.IncSalesCount
	}
	return 0
}

func (x *VideoTrendDTO) GetIncSalesCountStr() string {
	if x != nil {
		return x.IncSalesCountStr
	}
	return ""
}

func (x *VideoTrendDTO) GetIncSalesGmv() float64 {
	if x != nil {
		return x.IncSalesGmv
	}
	return 0
}

func (x *VideoTrendDTO) GetIncSalesGmvStr() string {
	if x != nil {
		return x.IncSalesGmvStr
	}
	return ""
}

func (x *VideoTrendDTO) GetIncFans() int64 {
	if x != nil {
		return x.IncFans
	}
	return 0
}

func (x *VideoTrendDTO) GetIncFansStr() string {
	if x != nil {
		return x.IncFansStr
	}
	return ""
}

func (x *VideoTrendDTO) GetGpm() float64 {
	if x != nil {
		return x.Gpm
	}
	return 0
}

func (x *VideoTrendDTO) GetGpmStr() string {
	if x != nil {
		return x.GpmStr
	}
	return ""
}

func (x *VideoTrendDTO) GetListTimeStr() string {
	if x != nil {
		return x.ListTimeStr
	}
	return ""
}

func (x *VideoTrendDTO) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

// 分页查询视频趋势请求
type ListVideoTrendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	AwemeId       string                 `protobuf:"bytes,2,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`       // 指定视频ID
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 起始日期，格式 "20060102"
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 结束日期，格式 "20060102"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideoTrendsRequest) Reset() {
	*x = ListVideoTrendsRequest{}
	mi := &file_v1_video_trend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideoTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoTrendsRequest) ProtoMessage() {}

func (x *ListVideoTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_trend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoTrendsRequest.ProtoReflect.Descriptor instead.
func (*ListVideoTrendsRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_trend_proto_rawDescGZIP(), []int{1}
}

func (x *ListVideoTrendsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListVideoTrendsRequest) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *ListVideoTrendsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListVideoTrendsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// 分页查询视频趋势响应
type ListVideoTrendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageResponse          `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Trends        []*VideoTrendDTO       `protobuf:"bytes,2,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideoTrendsResponse) Reset() {
	*x = ListVideoTrendsResponse{}
	mi := &file_v1_video_trend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideoTrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoTrendsResponse) ProtoMessage() {}

func (x *ListVideoTrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_trend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoTrendsResponse.ProtoReflect.Descriptor instead.
func (*ListVideoTrendsResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_trend_proto_rawDescGZIP(), []int{2}
}

func (x *ListVideoTrendsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListVideoTrendsResponse) GetTrends() []*VideoTrendDTO {
	if x != nil {
		return x.Trends
	}
	return nil
}

var File_v1_video_trend_proto protoreflect.FileDescriptor

const file_v1_video_trend_proto_rawDesc = "" +
	"\n" +
	"\x14v1/video_trend.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a\rv1/page.proto\"\x94\v\n" +
	"\rVideoTrendDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x19\n" +
	"\baweme_id\x18\x04 \x01(\tR\aawemeId\x12\x1b\n" +
	"\tdate_code\x18\x05 \x01(\x05R\bdateCode\x12\x1d\n" +
	"\n" +
	"like_count\x18\x06 \x01(\x03R\tlikeCount\x12$\n" +
	"\x0elike_count_str\x18\a \x01(\tR\flikeCountStr\x12\x1f\n" +
	"\vshare_count\x18\b \x01(\x03R\n" +
	"shareCount\x12&\n" +
	"\x0fshare_count_str\x18\t \x01(\tR\rshareCountStr\x12#\n" +
	"\rcomment_count\x18\n" +
	" \x01(\x03R\fcommentCount\x12*\n" +
	"\x11comment_count_str\x18\v \x01(\tR\x0fcommentCountStr\x12#\n" +
	"\rcollect_count\x18\f \x01(\x03R\fcollectCount\x12*\n" +
	"\x11collect_count_str\x18\r \x01(\tR\x0fcollectCountStr\x12)\n" +
	"\x10interaction_rate\x18\x0e \x01(\x01R\x0finteractionRate\x120\n" +
	"\x14interaction_rate_str\x18\x0f \x01(\tR\x12interactionRateStr\x12$\n" +
	"\x0einc_like_count\x18\x10 \x01(\x03R\fincLikeCount\x12+\n" +
	"\x12inc_like_count_str\x18\x11 \x01(\tR\x0fincLikeCountStr\x12&\n" +
	"\x0finc_share_count\x18\x12 \x01(\x03R\rincShareCount\x12-\n" +
	"\x13inc_share_count_str\x18\x13 \x01(\tR\x10incShareCountStr\x12*\n" +
	"\x11inc_comment_count\x18\x14 \x01(\x03R\x0fincCommentCount\x121\n" +
	"\x15inc_comment_count_str\x18\x15 \x01(\tR\x12incCommentCountStr\x12*\n" +
	"\x11inc_collect_count\x18\x16 \x01(\x03R\x0fincCollectCount\x121\n" +
	"\x15inc_collect_count_str\x18\x17 \x01(\tR\x12incCollectCountStr\x12\x1f\n" +
	"\vsales_count\x18\x18 \x01(\x03R\n" +
	"salesCount\x12&\n" +
	"\x0fsales_count_str\x18\x19 \x01(\tR\rsalesCountStr\x12\x1b\n" +
	"\tsales_gmv\x18\x1a \x01(\x01R\bsalesGmv\x12\"\n" +
	"\rsales_gmv_str\x18\x1b \x01(\tR\vsalesGmvStr\x12\x12\n" +
	"\x04fans\x18\x1c \x01(\x03R\x04fans\x12\x19\n" +
	"\bfans_str\x18\x1d \x01(\tR\afansStr\x12&\n" +
	"\x0finc_sales_count\x18\x1e \x01(\x03R\rincSalesCount\x12-\n" +
	"\x13inc_sales_count_str\x18\x1f \x01(\tR\x10incSalesCountStr\x12\"\n" +
	"\rinc_sales_gmv\x18  \x01(\x01R\vincSalesGmv\x12)\n" +
	"\x11inc_sales_gmv_str\x18! \x01(\tR\x0eincSalesGmvStr\x12\x19\n" +
	"\binc_fans\x18\" \x01(\x03R\aincFans\x12 \n" +
	"\finc_fans_str\x18# \x01(\tR\n" +
	"incFansStr\x12\x10\n" +
	"\x03gpm\x18$ \x01(\x01R\x03gpm\x12\x17\n" +
	"\agpm_str\x18% \x01(\tR\x06gpmStr\x12\"\n" +
	"\rlist_time_str\x18& \x01(\tR\vlistTimeStr\x12\x1d\n" +
	"\n" +
	"time_stamp\x18' \x01(\x03R\ttimeStamp\"\x8f\x01\n" +
	"\x16ListVideoTrendsRequest\x12 \n" +
	"\x04page\x18\x01 \x01(\v2\f.PageRequestR\x04page\x12\x19\n" +
	"\baweme_id\x18\x02 \x01(\tR\aawemeId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"g\n" +
	"\x17ListVideoTrendsResponse\x12!\n" +
	"\x04page\x18\x01 \x01(\v2\r.PageResponseR\x04page\x12)\n" +
	"\x06trends\x18\x02 \x03(\v2\x11.v1.VideoTrendDTOR\x06trends2\x81\x01\n" +
	"\x11VideoTrendService\x12l\n" +
	"\x0fListVideoTrends\x12\x1a.v1.ListVideoTrendsRequest\x1a\x1b.v1.ListVideoTrendsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/video_trends/listB\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_video_trend_proto_rawDescOnce sync.Once
	file_v1_video_trend_proto_rawDescData []byte
)

func file_v1_video_trend_proto_rawDescGZIP() []byte {
	file_v1_video_trend_proto_rawDescOnce.Do(func() {
		file_v1_video_trend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_video_trend_proto_rawDesc), len(file_v1_video_trend_proto_rawDesc)))
	})
	return file_v1_video_trend_proto_rawDescData
}

var file_v1_video_trend_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_video_trend_proto_goTypes = []any{
	(*VideoTrendDTO)(nil),           // 0: v1.VideoTrendDTO
	(*ListVideoTrendsRequest)(nil),  // 1: v1.ListVideoTrendsRequest
	(*ListVideoTrendsResponse)(nil), // 2: v1.ListVideoTrendsResponse
	(*PageRequest)(nil),             // 3: PageRequest
	(*PageResponse)(nil),            // 4: PageResponse
}
var file_v1_video_trend_proto_depIdxs = []int32{
	3, // 0: v1.ListVideoTrendsRequest.page:type_name -> PageRequest
	4, // 1: v1.ListVideoTrendsResponse.page:type_name -> PageResponse
	0, // 2: v1.ListVideoTrendsResponse.trends:type_name -> v1.VideoTrendDTO
	1, // 3: v1.VideoTrendService.ListVideoTrends:input_type -> v1.ListVideoTrendsRequest
	2, // 4: v1.VideoTrendService.ListVideoTrends:output_type -> v1.ListVideoTrendsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_video_trend_proto_init() }
func file_v1_video_trend_proto_init() {
	if File_v1_video_trend_proto != nil {
		return
	}
	file_v1_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_video_trend_proto_rawDesc), len(file_v1_video_trend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_video_trend_proto_goTypes,
		DependencyIndexes: file_v1_video_trend_proto_depIdxs,
		MessageInfos:      file_v1_video_trend_proto_msgTypes,
	}.Build()
	File_v1_video_trend_proto = out.File
	file_v1_video_trend_proto_goTypes = nil
	file_v1_video_trend_proto_depIdxs = nil
}
