// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.20.3
// source: v1/video_trend.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationVideoTrendServiceListVideoTrends = "/v1.VideoTrendService/ListVideoTrends"

type VideoTrendServiceHTTPServer interface {
	// ListVideoTrends 分页查询视频趋势信息
	ListVideoTrends(context.Context, *ListVideoTrendsRequest) (*ListVideoTrendsResponse, error)
}

func RegisterVideoTrendServiceHTTPServer(s *http.Server, srv VideoTrendServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/video_trends/list", _VideoTrendService_ListVideoTrends0_HTTP_Handler(srv))
}

func _VideoTrendService_ListVideoTrends0_HTTP_Handler(srv VideoTrendServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListVideoTrendsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVideoTrendServiceListVideoTrends)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListVideoTrends(ctx, req.(*ListVideoTrendsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListVideoTrendsResponse)
		return ctx.Result(200, reply)
	}
}

type VideoTrendServiceHTTPClient interface {
	ListVideoTrends(ctx context.Context, req *ListVideoTrendsRequest, opts ...http.CallOption) (rsp *ListVideoTrendsResponse, err error)
}

type VideoTrendServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewVideoTrendServiceHTTPClient(client *http.Client) VideoTrendServiceHTTPClient {
	return &VideoTrendServiceHTTPClientImpl{client}
}

func (c *VideoTrendServiceHTTPClientImpl) ListVideoTrends(ctx context.Context, in *ListVideoTrendsRequest, opts ...http.CallOption) (*ListVideoTrendsResponse, error) {
	var out ListVideoTrendsResponse
	pattern := "/v1/video_trends/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationVideoTrendServiceListVideoTrends))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
