// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: v1/video_trend.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoTrendService_ListVideoTrends_FullMethodName = "/v1.VideoTrendService/ListVideoTrends"
)

// VideoTrendServiceClient is the client API for VideoTrendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VideoTrendService 提供视频趋势数据的查询服务
type VideoTrendServiceClient interface {
	// 分页查询视频趋势信息
	ListVideoTrends(ctx context.Context, in *ListVideoTrendsRequest, opts ...grpc.CallOption) (*ListVideoTrendsResponse, error)
}

type videoTrendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoTrendServiceClient(cc grpc.ClientConnInterface) VideoTrendServiceClient {
	return &videoTrendServiceClient{cc}
}

func (c *videoTrendServiceClient) ListVideoTrends(ctx context.Context, in *ListVideoTrendsRequest, opts ...grpc.CallOption) (*ListVideoTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideoTrendsResponse)
	err := c.cc.Invoke(ctx, VideoTrendService_ListVideoTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoTrendServiceServer is the server API for VideoTrendService service.
// All implementations must embed UnimplementedVideoTrendServiceServer
// for forward compatibility.
//
// VideoTrendService 提供视频趋势数据的查询服务
type VideoTrendServiceServer interface {
	// 分页查询视频趋势信息
	ListVideoTrends(context.Context, *ListVideoTrendsRequest) (*ListVideoTrendsResponse, error)
	mustEmbedUnimplementedVideoTrendServiceServer()
}

// UnimplementedVideoTrendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoTrendServiceServer struct{}

func (UnimplementedVideoTrendServiceServer) ListVideoTrends(context.Context, *ListVideoTrendsRequest) (*ListVideoTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVideoTrends not implemented")
}
func (UnimplementedVideoTrendServiceServer) mustEmbedUnimplementedVideoTrendServiceServer() {}
func (UnimplementedVideoTrendServiceServer) testEmbeddedByValue()                           {}

// UnsafeVideoTrendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoTrendServiceServer will
// result in compilation errors.
type UnsafeVideoTrendServiceServer interface {
	mustEmbedUnimplementedVideoTrendServiceServer()
}

func RegisterVideoTrendServiceServer(s grpc.ServiceRegistrar, srv VideoTrendServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoTrendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoTrendService_ServiceDesc, srv)
}

func _VideoTrendService_ListVideoTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideoTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoTrendServiceServer).ListVideoTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoTrendService_ListVideoTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoTrendServiceServer).ListVideoTrends(ctx, req.(*ListVideoTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoTrendService_ServiceDesc is the grpc.ServiceDesc for VideoTrendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoTrendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VideoTrendService",
	HandlerType: (*VideoTrendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVideoTrends",
			Handler:    _VideoTrendService_ListVideoTrends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/video_trend.proto",
}
