// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: v1/video_rank.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VideoRank 查询请求参数
type VideoRankQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwemeId       string                 `protobuf:"bytes,1,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`    // 视频唯一ID
	RankType      string                 `protobuf:"bytes,2,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"` // 排名类型，例如"hot", "view", "like"
	RankDate      string                 `protobuf:"bytes,3,opt,name=rank_date,json=rankDate,proto3" json:"rank_date,omitempty"` // 排名日期，格式如"2025-07-16"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRankQueryRequest) Reset() {
	*x = VideoRankQueryRequest{}
	mi := &file_v1_video_rank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRankQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRankQueryRequest) ProtoMessage() {}

func (x *VideoRankQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRankQueryRequest.ProtoReflect.Descriptor instead.
func (*VideoRankQueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{0}
}

func (x *VideoRankQueryRequest) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *VideoRankQueryRequest) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

func (x *VideoRankQueryRequest) GetRankDate() string {
	if x != nil {
		return x.RankDate
	}
	return ""
}

// VideoRank 查询响应
type VideoRankQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          *VideoRankDTO          `protobuf:"bytes,1,opt,name=rank,proto3" json:"rank,omitempty"` // 视频榜单信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRankQueryResponse) Reset() {
	*x = VideoRankQueryResponse{}
	mi := &file_v1_video_rank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRankQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRankQueryResponse) ProtoMessage() {}

func (x *VideoRankQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRankQueryResponse.ProtoReflect.Descriptor instead.
func (*VideoRankQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{1}
}

func (x *VideoRankQueryResponse) GetRank() *VideoRankDTO {
	if x != nil {
		return x.Rank
	}
	return nil
}

// 分页查询请求
type ListVideoRankRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 嵌入分页请求
	Page *PageRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// 排名类型，例如"day", "week", "month"
	RankType string `protobuf:"bytes,2,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"`
	// 排名日期，格式如"20250716"
	RankDate      string `protobuf:"bytes,3,opt,name=rank_date,json=rankDate,proto3" json:"rank_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideoRankRequest) Reset() {
	*x = ListVideoRankRequest{}
	mi := &file_v1_video_rank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideoRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoRankRequest) ProtoMessage() {}

func (x *ListVideoRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoRankRequest.ProtoReflect.Descriptor instead.
func (*ListVideoRankRequest) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{2}
}

func (x *ListVideoRankRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListVideoRankRequest) GetRankType() string {
	if x != nil {
		return x.RankType
	}
	return ""
}

func (x *ListVideoRankRequest) GetRankDate() string {
	if x != nil {
		return x.RankDate
	}
	return ""
}

// 分页查询响应
type ListVideoRankResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 嵌入分页响应
	Page *PageResponse `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	// 视频榜单信息列表
	Ranks         []*VideoRankDTO `protobuf:"bytes,2,rep,name=ranks,proto3" json:"ranks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideoRankResponse) Reset() {
	*x = ListVideoRankResponse{}
	mi := &file_v1_video_rank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideoRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoRankResponse) ProtoMessage() {}

func (x *ListVideoRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoRankResponse.ProtoReflect.Descriptor instead.
func (*ListVideoRankResponse) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{3}
}

func (x *ListVideoRankResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListVideoRankResponse) GetRanks() []*VideoRankDTO {
	if x != nil {
		return x.Ranks
	}
	return nil
}

// 榜单视频榜结构
type VideoRankDTO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 创建时间
	CreatedAt string `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 榜单周期类型，如日榜、周榜
	PeriodType string `protobuf:"bytes,4,opt,name=period_type,json=periodType,proto3" json:"period_type,omitempty"`
	// 榜单日期
	RankDate string `protobuf:"bytes,5,opt,name=rank_date,json=rankDate,proto3" json:"rank_date,omitempty"`
	// 榜单开始日期
	StartDate string `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// 榜单结束日期
	EndDate string `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// 视频信息
	// 抖音视频ID
	AwemeId string `protobuf:"bytes,8,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`
	// 视频封面URL
	AwemeCoverUrl string `protobuf:"bytes,9,opt,name=aweme_cover_url,json=awemeCoverUrl,proto3" json:"aweme_cover_url,omitempty"`
	// 视频描述
	AwemeDesc string `protobuf:"bytes,10,opt,name=aweme_desc,json=awemeDesc,proto3" json:"aweme_desc,omitempty"`
	// 视频发布时间
	AwemePubTime string `protobuf:"bytes,11,opt,name=aweme_pub_time,json=awemePubTime,proto3" json:"aweme_pub_time,omitempty"`
	// 视频分享链接
	AwemeShareUrl string `protobuf:"bytes,12,opt,name=aweme_share_url,json=awemeShareUrl,proto3" json:"aweme_share_url,omitempty"`
	// 视频时长字符串
	DurationStr string `protobuf:"bytes,13,opt,name=duration_str,json=durationStr,proto3" json:"duration_str,omitempty"`
	// 视频分数字符串
	AwemeScoreStr string `protobuf:"bytes,14,opt,name=aweme_score_str,json=awemeScoreStr,proto3" json:"aweme_score_str,omitempty"`
	// 商品信息
	// 商品ID
	GoodsId string `protobuf:"bytes,15,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	// 商品标题
	GoodsTitle string `protobuf:"bytes,16,opt,name=goods_title,json=goodsTitle,proto3" json:"goods_title,omitempty"`
	// 商品封面URL
	GoodsCoverUrl string `protobuf:"bytes,17,opt,name=goods_cover_url,json=goodsCoverUrl,proto3" json:"goods_cover_url,omitempty"`
	// 商品价格区间
	GoodsPriceRange string `protobuf:"bytes,18,opt,name=goods_price_range,json=goodsPriceRange,proto3" json:"goods_price_range,omitempty"`
	// 商品价格
	GoodsPrice float64 `protobuf:"fixed64,19,opt,name=goods_price,json=goodsPrice,proto3" json:"goods_price,omitempty"`
	// 成本比例
	CosRatio string `protobuf:"bytes,20,opt,name=cos_ratio,json=cosRatio,proto3" json:"cos_ratio,omitempty"`
	// 佣金金额
	CommissionPrice string `protobuf:"bytes,21,opt,name=commission_price,json=commissionPrice,proto3" json:"commission_price,omitempty"`
	// 店铺名称
	ShopName string `protobuf:"bytes,22,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	// 品牌名称
	BrandName string `protobuf:"bytes,23,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	// 商品类目
	CategoryNames string `protobuf:"bytes,24,opt,name=category_names,json=categoryNames,proto3" json:"category_names,omitempty"`
	// 博主信息
	// 博主ID
	BloggerId int32 `protobuf:"varint,25,opt,name=blogger_id,json=bloggerId,proto3" json:"blogger_id,omitempty"`
	// 博主UID
	BloggerUid string `protobuf:"bytes,26,opt,name=blogger_uid,json=bloggerUid,proto3" json:"blogger_uid,omitempty"`
	// 博主昵称
	BloggerName string `protobuf:"bytes,27,opt,name=blogger_name,json=bloggerName,proto3" json:"blogger_name,omitempty"`
	// 博主头像
	BloggerAvatar string `protobuf:"bytes,28,opt,name=blogger_avatar,json=bloggerAvatar,proto3" json:"blogger_avatar,omitempty"`
	// 博主粉丝数
	BloggerFansNum int32 `protobuf:"varint,29,opt,name=blogger_fans_num,json=bloggerFansNum,proto3" json:"blogger_fans_num,omitempty"`
	// 博主标签
	BloggerTag string `protobuf:"bytes,30,opt,name=blogger_tag,json=bloggerTag,proto3" json:"blogger_tag,omitempty"`
	// 榜单统计
	// 销量字符串
	SalesCountStr string `protobuf:"bytes,31,opt,name=sales_count_str,json=salesCountStr,proto3" json:"sales_count_str,omitempty"`
	// 累计销量字符串
	TotalSalesStr string `protobuf:"bytes,32,opt,name=total_sales_str,json=totalSalesStr,proto3" json:"total_sales_str,omitempty"`
	// 点赞增量字符串
	LikeCountIncStr string `protobuf:"bytes,33,opt,name=like_count_inc_str,json=likeCountIncStr,proto3" json:"like_count_inc_str,omitempty"`
	// 播放增量字符串
	PlayCountIncStr string `protobuf:"bytes,34,opt,name=play_count_inc_str,json=playCountIncStr,proto3" json:"play_count_inc_str,omitempty"`
	// 元数据
	// 原始元数据JSON
	RawJson       string `protobuf:"bytes,35,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRankDTO) Reset() {
	*x = VideoRankDTO{}
	mi := &file_v1_video_rank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRankDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRankDTO) ProtoMessage() {}

func (x *VideoRankDTO) ProtoReflect() protoreflect.Message {
	mi := &file_v1_video_rank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRankDTO.ProtoReflect.Descriptor instead.
func (*VideoRankDTO) Descriptor() ([]byte, []int) {
	return file_v1_video_rank_proto_rawDescGZIP(), []int{4}
}

func (x *VideoRankDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoRankDTO) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoRankDTO) GetPeriodType() string {
	if x != nil {
		return x.PeriodType
	}
	return ""
}

func (x *VideoRankDTO) GetRankDate() string {
	if x != nil {
		return x.RankDate
	}
	return ""
}

func (x *VideoRankDTO) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *VideoRankDTO) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *VideoRankDTO) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *VideoRankDTO) GetAwemeCoverUrl() string {
	if x != nil {
		return x.AwemeCoverUrl
	}
	return ""
}

func (x *VideoRankDTO) GetAwemeDesc() string {
	if x != nil {
		return x.AwemeDesc
	}
	return ""
}

func (x *VideoRankDTO) GetAwemePubTime() string {
	if x != nil {
		return x.AwemePubTime
	}
	return ""
}

func (x *VideoRankDTO) GetAwemeShareUrl() string {
	if x != nil {
		return x.AwemeShareUrl
	}
	return ""
}

func (x *VideoRankDTO) GetDurationStr() string {
	if x != nil {
		return x.DurationStr
	}
	return ""
}

func (x *VideoRankDTO) GetAwemeScoreStr() string {
	if x != nil {
		return x.AwemeScoreStr
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsTitle() string {
	if x != nil {
		return x.GoodsTitle
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsCoverUrl() string {
	if x != nil {
		return x.GoodsCoverUrl
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsPriceRange() string {
	if x != nil {
		return x.GoodsPriceRange
	}
	return ""
}

func (x *VideoRankDTO) GetGoodsPrice() float64 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *VideoRankDTO) GetCosRatio() string {
	if x != nil {
		return x.CosRatio
	}
	return ""
}

func (x *VideoRankDTO) GetCommissionPrice() string {
	if x != nil {
		return x.CommissionPrice
	}
	return ""
}

func (x *VideoRankDTO) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *VideoRankDTO) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *VideoRankDTO) GetCategoryNames() string {
	if x != nil {
		return x.CategoryNames
	}
	return ""
}

func (x *VideoRankDTO) GetBloggerId() int32 {
	if x != nil {
		return x.BloggerId
	}
	return 0
}

func (x *VideoRankDTO) GetBloggerUid() string {
	if x != nil {
		return x.BloggerUid
	}
	return ""
}

func (x *VideoRankDTO) GetBloggerName() string {
	if x != nil {
		return x.BloggerName
	}
	return ""
}

func (x *VideoRankDTO) GetBloggerAvatar() string {
	if x != nil {
		return x.BloggerAvatar
	}
	return ""
}

func (x *VideoRankDTO) GetBloggerFansNum() int32 {
	if x != nil {
		return x.BloggerFansNum
	}
	return 0
}

func (x *VideoRankDTO) GetBloggerTag() string {
	if x != nil {
		return x.BloggerTag
	}
	return ""
}

func (x *VideoRankDTO) GetSalesCountStr() string {
	if x != nil {
		return x.SalesCountStr
	}
	return ""
}

func (x *VideoRankDTO) GetTotalSalesStr() string {
	if x != nil {
		return x.TotalSalesStr
	}
	return ""
}

func (x *VideoRankDTO) GetLikeCountIncStr() string {
	if x != nil {
		return x.LikeCountIncStr
	}
	return ""
}

func (x *VideoRankDTO) GetPlayCountIncStr() string {
	if x != nil {
		return x.PlayCountIncStr
	}
	return ""
}

func (x *VideoRankDTO) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

var File_v1_video_rank_proto protoreflect.FileDescriptor

const file_v1_video_rank_proto_rawDesc = "" +
	"\n" +
	"\x13v1/video_rank.proto\x1a\x1cgoogle/api/annotations.proto\x1a\rv1/page.proto\"l\n" +
	"\x15VideoRankQueryRequest\x12\x19\n" +
	"\baweme_id\x18\x01 \x01(\tR\aawemeId\x12\x1b\n" +
	"\trank_type\x18\x02 \x01(\tR\brankType\x12\x1b\n" +
	"\trank_date\x18\x03 \x01(\tR\brankDate\";\n" +
	"\x16VideoRankQueryResponse\x12!\n" +
	"\x04rank\x18\x01 \x01(\v2\r.VideoRankDTOR\x04rank\"r\n" +
	"\x14ListVideoRankRequest\x12 \n" +
	"\x04page\x18\x01 \x01(\v2\f.PageRequestR\x04page\x12\x1b\n" +
	"\trank_type\x18\x02 \x01(\tR\brankType\x12\x1b\n" +
	"\trank_date\x18\x03 \x01(\tR\brankDate\"_\n" +
	"\x15ListVideoRankResponse\x12!\n" +
	"\x04page\x18\x01 \x01(\v2\r.PageResponseR\x04page\x12#\n" +
	"\x05ranks\x18\x02 \x03(\v2\r.VideoRankDTOR\x05ranks\"\xa6\t\n" +
	"\fVideoRankDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vperiod_type\x18\x04 \x01(\tR\n" +
	"periodType\x12\x1b\n" +
	"\trank_date\x18\x05 \x01(\tR\brankDate\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\x19\n" +
	"\baweme_id\x18\b \x01(\tR\aawemeId\x12&\n" +
	"\x0faweme_cover_url\x18\t \x01(\tR\rawemeCoverUrl\x12\x1d\n" +
	"\n" +
	"aweme_desc\x18\n" +
	" \x01(\tR\tawemeDesc\x12$\n" +
	"\x0eaweme_pub_time\x18\v \x01(\tR\fawemePubTime\x12&\n" +
	"\x0faweme_share_url\x18\f \x01(\tR\rawemeShareUrl\x12!\n" +
	"\fduration_str\x18\r \x01(\tR\vdurationStr\x12&\n" +
	"\x0faweme_score_str\x18\x0e \x01(\tR\rawemeScoreStr\x12\x19\n" +
	"\bgoods_id\x18\x0f \x01(\tR\agoodsId\x12\x1f\n" +
	"\vgoods_title\x18\x10 \x01(\tR\n" +
	"goodsTitle\x12&\n" +
	"\x0fgoods_cover_url\x18\x11 \x01(\tR\rgoodsCoverUrl\x12*\n" +
	"\x11goods_price_range\x18\x12 \x01(\tR\x0fgoodsPriceRange\x12\x1f\n" +
	"\vgoods_price\x18\x13 \x01(\x01R\n" +
	"goodsPrice\x12\x1b\n" +
	"\tcos_ratio\x18\x14 \x01(\tR\bcosRatio\x12)\n" +
	"\x10commission_price\x18\x15 \x01(\tR\x0fcommissionPrice\x12\x1b\n" +
	"\tshop_name\x18\x16 \x01(\tR\bshopName\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x17 \x01(\tR\tbrandName\x12%\n" +
	"\x0ecategory_names\x18\x18 \x01(\tR\rcategoryNames\x12\x1d\n" +
	"\n" +
	"blogger_id\x18\x19 \x01(\x05R\tbloggerId\x12\x1f\n" +
	"\vblogger_uid\x18\x1a \x01(\tR\n" +
	"bloggerUid\x12!\n" +
	"\fblogger_name\x18\x1b \x01(\tR\vbloggerName\x12%\n" +
	"\x0eblogger_avatar\x18\x1c \x01(\tR\rbloggerAvatar\x12(\n" +
	"\x10blogger_fans_num\x18\x1d \x01(\x05R\x0ebloggerFansNum\x12\x1f\n" +
	"\vblogger_tag\x18\x1e \x01(\tR\n" +
	"bloggerTag\x12&\n" +
	"\x0fsales_count_str\x18\x1f \x01(\tR\rsalesCountStr\x12&\n" +
	"\x0ftotal_sales_str\x18  \x01(\tR\rtotalSalesStr\x12+\n" +
	"\x12like_count_inc_str\x18! \x01(\tR\x0flikeCountIncStr\x12+\n" +
	"\x12play_count_inc_str\x18\" \x01(\tR\x0fplayCountIncStr\x12\x19\n" +
	"\braw_json\x18# \x01(\tR\arawJson2\xc7\x01\n" +
	"\tVideoRank\x12Z\n" +
	"\fGetVideoRank\x12\x16.VideoRankQueryRequest\x1a\x17.VideoRankQueryResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/video_rank\x12^\n" +
	"\rListVideoRank\x12\x15.ListVideoRankRequest\x1a\x16.ListVideoRankResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/video_rank/listB\x14Z\x12aresdata/api/v1;v1b\x06proto3"

var (
	file_v1_video_rank_proto_rawDescOnce sync.Once
	file_v1_video_rank_proto_rawDescData []byte
)

func file_v1_video_rank_proto_rawDescGZIP() []byte {
	file_v1_video_rank_proto_rawDescOnce.Do(func() {
		file_v1_video_rank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_video_rank_proto_rawDesc), len(file_v1_video_rank_proto_rawDesc)))
	})
	return file_v1_video_rank_proto_rawDescData
}

var file_v1_video_rank_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_video_rank_proto_goTypes = []any{
	(*VideoRankQueryRequest)(nil),  // 0: VideoRankQueryRequest
	(*VideoRankQueryResponse)(nil), // 1: VideoRankQueryResponse
	(*ListVideoRankRequest)(nil),   // 2: ListVideoRankRequest
	(*ListVideoRankResponse)(nil),  // 3: ListVideoRankResponse
	(*VideoRankDTO)(nil),           // 4: VideoRankDTO
	(*PageRequest)(nil),            // 5: PageRequest
	(*PageResponse)(nil),           // 6: PageResponse
}
var file_v1_video_rank_proto_depIdxs = []int32{
	4, // 0: VideoRankQueryResponse.rank:type_name -> VideoRankDTO
	5, // 1: ListVideoRankRequest.page:type_name -> PageRequest
	6, // 2: ListVideoRankResponse.page:type_name -> PageResponse
	4, // 3: ListVideoRankResponse.ranks:type_name -> VideoRankDTO
	0, // 4: VideoRank.GetVideoRank:input_type -> VideoRankQueryRequest
	2, // 5: VideoRank.ListVideoRank:input_type -> ListVideoRankRequest
	1, // 6: VideoRank.GetVideoRank:output_type -> VideoRankQueryResponse
	3, // 7: VideoRank.ListVideoRank:output_type -> ListVideoRankResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_video_rank_proto_init() }
func file_v1_video_rank_proto_init() {
	if File_v1_video_rank_proto != nil {
		return
	}
	file_v1_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_video_rank_proto_rawDesc), len(file_v1_video_rank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_video_rank_proto_goTypes,
		DependencyIndexes: file_v1_video_rank_proto_depIdxs,
		MessageInfos:      file_v1_video_rank_proto_msgTypes,
	}.Build()
	File_v1_video_rank_proto = out.File
	file_v1_video_rank_proto_goTypes = nil
	file_v1_video_rank_proto_depIdxs = nil
}
