.PHONY: fetch_video_rank
fetch_video_rank:
	go run . -conf ../../configs -task fetch:video_rank

.PHONY: fetch_video_trend
fetch_video_trend:
	go run . -conf ../../configs -task fetch:video_trend

.PHONY: fetch_video_trend_headless
fetch_video_trend_headless:
	go run . -conf ../../configs -task fetch:video_trend_headless
