server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://root:jayleonc@localhost:15432/aresdata?sslmode=disable&TimeZone=Asia/Shanghai
  redis:
    addr: 127.0.0.1:16379
    password: "123456"
    read_timeout: 0.2s
    write_timeout: 0.2s
  #  feigua:
  #    baseUrl: "http://118.31.20.20:8080"
  #    cookie: "PHPSESSID=tdn5sqcnh1ub2413v9n6ffdpgt; body_collapsed=0"
  #    throttle_min_wait_ms: 15000  # 80秒
  #    throttle_max_wait_ms: 20000 # 90秒
  datasources:
    - name: "feigua_headless_primary"
      type: "headless"
      base_url: "http://121.40.63.195:8085/"
      timeout: 180
      headless: true
      proxy: ""
      account_pool:
        - "configs/assets/feigua_account_1.json"
        - "configs/assets/feigua_account_2.json"
    - name: "other_site_headless" 
      type: "headless"
      base_url: "http://another-website.com/api/" 
      timeout: 120
      headless: true
      proxy: ""
      account_pool:
        - "configs/assets/other_site_account_1.json"
    - name: "feigua_http_backup"
      type: "http"
      base_url: "http://121.40.63.195:8080/"
      timeout: 30
      account_pool:
        - "configs/assets/http_account_1.json"

# 在文件末尾追加
job:
  fetchVideoRankCron: "0 2 * * *" # 每天2:00执行
