server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://root:jayleonc@localhost:15432/aresdata?sslmode=disable
  redis:
    addr: 127.0.0.1:16379
    password: "123456"
    read_timeout: 0.2s
    write_timeout: 0.2s
  feigua:
    baseUrl: "http://118.31.20.20:8080"
    cookie: "PHPSESSID=tdn5sqcnh1ub2413v9n6ffdpgt; body_collapsed=0"
    throttle_min_wait_ms: 80000  # 80秒
    throttle_max_wait_ms: 120000 # 120秒

# 在文件末尾追加
job:
  fetchVideoRankCron: "0 2 * * *" # 每天2:00执行
