server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://root:jayleonc@localhost:15432/aresdata?sslmode=disable&TimeZone=Asia/Shanghai
  redis:
    addr: 127.0.0.1:16379
    password: "123456"
    read_timeout: 0.2s
    write_timeout: 0.2s
  #  feigua:
  #    baseUrl: "http://118.31.20.20:8080"
  #    cookie: "PHPSESSID=tdn5sqcnh1ub2413v9n6ffdpgt; body_collapsed=0"
  #    throttle_min_wait_ms: 15000  # 80秒
  #    throttle_max_wait_ms: 20000 # 90秒
  feigua:
    baseUrl: "http://121.40.63.195:8085"
    cookie: "il=2CD2D1033AE2554CF43E3DD40B5D08AC; mu=; DYHHB_Session_2=4F390ED5B7E47D2FA5E7073C3BA4994F; body_collapsed=1"
    throttle_min_wait_ms: 35000  # 80秒
    throttle_start_wait_ms: 20000
    throttle_max_wait_ms: 40000 # 90秒


    cookie_path: "configs/assets/cookies.json" # 【方案一】指向存放 cookie 的文件路径
    user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" # 推荐使用一个真实的 User-Agent
    # --- ↓↓↓↓ 新增的无头浏览器核心配置 ↓↓↓↓ ---
    headless: true # 【关键】true 表示在服务器上静默运行，false 会在本地弹出浏览器界面，用于调试
    proxy: "" # 如果需要代理，在这里填写，例如 "http://user:pass@host:port"
    timeout: 90 # 【关键】单个采集任务的超时时间（秒），无头浏览器启动和加载慢，建议不少于60秒
    cookie_content: "" # 【方案二】如果不想用文件，可以直接把 Cookie 的 JSON 内容粘贴在这里（注意YAML的转义），优先级高于 cookie_path

# 在文件末尾追加
job:
  fetchVideoRankCron: "0 2 * * *" # 每天2:00执行
